### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#1]
Trial.
Experimenting with labels.

**Comment by canberkboun9** [comment]
Done somethings and closing this issue.

[deneme](https://www.google.com/search?q=asdas&oq=asdas&aqs=chrome..69i57j0i271j35i39i362j0i271j69i60l4.348j0j7&sourceid=chrome&ie=UTF-8)

**Comment by canberkboun9** [comment]
Reopening the issue because it is not a good issue.

**Comment by palahb** [comment]
This is a test.

**Comment by mehmetemreakbulut** [comment]
It's a invalid issue. Closing it.
