### ISSUE TITLE
General research to use Slack Workspace effectively

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#10]
# Some features will be added to Slack:  
- Slack bots  
- Channels to classify the teams and tasks.  
- Google Calendar  
- Birthday Bot 🎂

**Comment by canberkboun9** [comment]
Reviewed the first (root) comment, edited it to look like a list.

**Comment by mehmetemreakbulut** [comment]
We can write our suggestions in Slack, so I am closing the issue.
