### ISSUE TITLE
Practice App: Implementing API for article-info - Unit Tests

### ISSUE THREAD

**Issue by makifyilmaz** [bounswe/bounswe2022group5#108]
Tests for the article-info API of the Practice App will be implemented using the TestCase library in django.test.
Further information related to the article-info API can be found in issue #97 .

**Tasks:**
*  Tests for urls will be implemented.
*  Tests for views will be implemented.
*  Tests for forms will be implemented.
*  Tests for models will be implemented.

**Reviewers:** @canberkboun9 , @oguzhandemirelx 
Task Deadline : 14.05.2022 16:00
Review Deadline: 14.05.2022 20:00

**Comment by makifyilmaz** [comment]
Tests for views, URLs and forms are implemented and pull request #132  is opened for merging it.

**Comment by makifyilmaz** [comment]
The code is merged. Therefore I am closing the issue.

**Comment by canberkboun9** [comment]
Reminder: Adding the PR from the right of this issue page "Development" would automatically binds the PR with this issue, and closes the issue when the PR is merged.
