### ISSUE TITLE
Adding group members to Wiki Page

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#11]
## Group members and their links are added to wiki page

**Comment by mehmetemreakbulut** [comment]
Some personal wiki pages have not been opened yet. We will follow up [here](https://github.com/bounswe/bounswe2022group5/wiki) until all personal wiki pages are created.

**Comment by enginoguzhansenol** [comment]
Added my personal wiki page to the group's wiki page.

> Some personal wiki pages have not been opened yet. We will follow up [here](https://github.com/bounswe/bounswe2022group5/wiki) until all personal wiki pages are created.

**Comment by mehmetemreakbulut** [comment]
Everybody is added. Closing issue.

**Comment by canberkboun9** [comment]
All members seem to be added. Closing the issue.

**Comment by mehmetemreakbulut** [comment]
Everybody is added. Closing issue.
