### ISSUE TITLE
Practice App: Bug Fixes related misdirecting urls

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#113]
Description

There is a bug in urls, /post/ endpoint is directing user to category page.
 I am going to check api urls and template names.

Task Deadline: 16.05.2022 21:00
Review Deadline: 16.05.2022 20:00

Reviewers: @yavuuzsameet

**Comment by yavuuzsameet** [comment]
I had been struggling with this issue for the whole day. Thanks for bringing it up.

**Comment by yavuuzsameet** [comment]
I have merged the related branch to master. Your solution seems to be on point. Thanks again. I am now closing the issue. Bug fixed.

**Comment by yavuuzsameet** [comment]
There are still problems regarding the same issue. This time ```/post``` url redirects to the comment app user interface. I should change the template names as @burakmert236 specified in #114.
