### ISSUE TITLE
Practice-App: Implementing API for post-info - Unit Tests 

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#115]
**To do:**

For post-info API:  

- Unit tests for views will be written.
- Unit tests for forms will be written.
- Unit tests for urls will be written. 

Task Deadline: 16.05.2022 16:00
Review Deadline: 16.05.2022 20:00

Reviewers: @yavuuzsameet , @Keremgunduz7

**Comment by kardelendemiral** [comment]
Tests are implemented and a pull request is created.

See: #116

**Comment by yavuuzsameet** [comment]
I have merged the relevant branch (#116) with the master. The issue can be closed if there are no additional adjustments that you want to make.

**Comment by kardelendemiral** [comment]
Thank you for the review! I am closing the issue now that my commit is merged.
