### ISSUE TITLE
Practice-App: Implementing Login and Home Page

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#121]
### Login Page
* A login page is used to see the home page of practice app.
* Username and password is required.
* APIs use the authenticated user after the login step.

### Home Page
* Before the deployment, a home page which contains all the enpoints of the group members will be created. 
* A user can click the cards in the page to use the APIs.
* Cards show the information about apps of the Group 5 members: 
   * Creator 
   * Functionality
   *  Endpoint.

No spesific reviewers is required. All members of Group 5 can give feedback about page. This pages will be reviewed in the upcoming meeting.

**Comment by mehmetemreakbulut** [comment]
* PR is created. #127 
* Review needed @yavuuzsameet 
* Login and Home Page:

https://user-images.githubusercontent.com/74511892/168760812-efa02e99-607a-4838-bed2-6dfff0db2e09.mp4


https://user-images.githubusercontent.com/74511892/168760999-7e793950-6522-4e08-b786-c7ed20490ffa.mp4

**Comment by yavuuzsameet** [comment]
Very well to my eyes, I am now checking related pull request.

**Comment by yavuuzsameet** [comment]
I have a question related to this functionality. Is the user information stored in the session?
