### ISSUE TITLE
Organizing the pages in wiki using sidebar

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#13]
An initial sidebar has been created to categorize pages more easily.

**Comment by canberkboun9** [comment]
### Review:  
- Enhancement label is supposed to be used in cases like, new features, code enhancements, new mechanisms in the product, etc. 
- We should find a new label for github wiki page enhancements or just use Documentation.

**Comment by canberkboun9** [comment]
Added assignees.
Review: Using _Sidebar feature or simply the button to add a sidebar, this task is done. This task was also mentioned in [Issue #2](https://github.com/bounswe/bounswe2022group5/issues/2). While creating the sidebar, Emre created a part for the meetings mentioned in the Issue #2. I reviewed it and added a listing mechanism, ending the issue with the sidebar I had before.

**Comment by yavuuzsameet** [comment]
@mehmetemreakbulut can you please move the Git and Github wiki page under the Research tab in the sidebar?

**Comment by mehmetemreakbulut** [comment]
> @mehmetemreakbulut can you please move the Git and Github wiki page under the Research tab in the sidebar?

it's done.

**Comment by mehmetemreakbulut** [comment]
Sidebar is working successfully. Closing the issue.
