### ISSUE TITLE
Practice App: Implementing the API for Rate Comment - Unit Tests

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#134]
**Description:**
Unit tests for rate-comment endpoint will be written.

**Reviewers:** @bbenginbestas @yavuuzsameet

**Task Deadline:** 19.05.2022 19:00
**Review Deadline:** 19.05.2022 19:00

**Comment by yavuuzsameet** [comment]
The deadline for this task is 19.05.2022 19:00, i.e. just before our dockerization and deployment meeting.
