### ISSUE TITLE
Practice-App: Class Diagram

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#142]
**Description:**

The class diagram which is completed during [Meeting 12.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-12.1) will be uploaded to a [wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Practice-App:-Class-Diagram).

**Reviewer:** @canberkboun9 

**Task Deadline:** 20.05.2022 17:00
**Review Deadline:** 20.05.2022 20:00

**Comment by yavuuzsameet** [comment]
Class diagram uploaded to a newly created [wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Practice-App:-Class-Diagram) and sidebar updated. Need review.

**Comment by canberkboun9** [comment]
The image is clear, its pixel quality is good. Link is correct, it is added to the sidebar and wiki home page correctly. 
Nice work! Closing the issue.

**Comment by canberkboun9** [comment]
Detected error in Article Class first function, constructor. Edited it. Some other modifications can be added, reopening the issue

**Comment by palahb** [comment]
I also made some corrections in the Comment and Article class. This version of the class digram seems OK I think.

**Comment by yavuuzsameet** [comment]
Updated the wiki page.

**Comment by canberkboun9** [comment]
Final upload seems alright! Thanks, closing the issue.
