### ISSUE TITLE
Practice-App: Implementing API for article-info - Bug Fix

### ISSUE THREAD

**Issue by makifyilmaz** [bounswe/bounswe2022group5#144]
There occurs a problem about misdirection in the article-info API when the user tries to go to the  previous page. Therefore "Home" and "Back" buttons will be added to the User Interface.
"Home" button will redirect to the main page of the project.
"Back" button will redirect to the previous page.

Reviewers: @canberkboun9 @oguzhandemirelx 
Task Deadline: 19.05.2022 16:00
Review Deadline: 19.05.2022 20:00

**Comment by canberkboun9** [comment]
Nice work. I merged the PR.

**Comment by makifyilmaz** [comment]
The code is merged. Therefore I am closing the issue.
