### ISSUE TITLE
Practice-App: Uploading Use Case Diagram

### ISSUE THREAD

**Issue by makifyilmaz** [bounswe/bounswe2022group5#145]
#### Description:
The Use Case Diagram completed in [Meeting 12.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-12.1) will be uploaded to a wiki page.

Reviewer: @palahb 
Task Deadline: 20.05.2022 17:00
Review Deadline: 20.05.2022 20:00

**Comment by makifyilmaz** [comment]
The use case diagram for the practice app is uploaded to a [wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Practice-App:-Use-Case-Diagram) and also added to the sidebar.

**Comment by palahb** [comment]
It seems OK. Thank you Akif!
