### ISSUE TITLE
Practice-app: post-info API Documentation Preparation

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#149]
**To do:**
A documentation should be prepared for the API post-info used in our practice-app using Postman.

**Task Deadline:** 20.05.2022 16:00
**Review Deadline:** 20.05.2022 20:00

**Reviewer:** @yavuuzsameet

**Comment by kardelendemiral** [comment]
I prepared the documentation using Postman. You can reach it from the below link:

[post-info API documentation](https://documenter.getpostman.com/view/20881320/UyxnEQnH)

Need review.

**Comment by yavuuzsameet** [comment]
Sample calls and their responses are crystal clear. However, it is currently requesting to localhost. We may need to update the documentation after deployment.

**Comment by kardelendemiral** [comment]
Yes, I will update it after the deployment. Thanks for the review.
