### ISSUE TITLE
Creating a Poll (or another method) to determine the weekly meeting date

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#16]
# The meeting date will be determined based on group members' availability. 
* All the members will fill their own available hours from https://www.when2meet.com/?14867877-RnxZX.
* The meeting time will be finalized by the results.
* According to the poll team meetings will be on tuesdays or/and wednesdays at 21.00 o'clock .

**Comment by busetolunay** [comment]
meeting day and hour is determined
