### ISSUE TITLE
Practice App: Uploading Sequence Diagrams

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#161]
Description:
The Sequence Diagrams for Practice App will be uploaded to the wiki page.

Reviewer: @bbenginbestas 
Task Deadline: 20.05.2022 17:00
Review Deadline: 20.05.2022 20:00

**Comment by enginoguzhansenol** [comment]
I uploaded all the sequence diagrams that were created. After adding the missing ones, we can close this issue.

**Comment by enginoguzhansenol** [comment]
I added the missing ones. Yet, a Sequence Diagram for the Update Category is not made. This section is left blank. Other all sequence diagrams are added to the relative wiki page.

**Comment by bbenginbestas** [comment]
The sequence diagrams are added in an organized way and they are well-made. I don't see anything wrong. It looks great.
