### ISSUE TITLE
Preparing a Guide For Running Our Application

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#162]
#### Description:
A brief guide explaning how to run our app by using docker will be created and placed in the read.me file of our practice app. 

#### Review Deadline: 20.05.2022 20:00

**Comment by palahb** [comment]
I prepared the guide, explained:
- How to run our app directly and by using docker,
- How to test our individual apps. 

I put the guide into the [README.md file](https://github.com/bounswe/bounswe2022group5/blob/master/practice-app/README.md) of our practice app and pushed the changed version directly to the master branch. 

@mehmetemreakbulut , can you review it?

**Comment by mehmetemreakbulut** [comment]
I reviewed. Everything looks fine.
