### ISSUE TITLE
Creating a new Issue Template

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#169]
**Description:**

The issue template that is going to be used for the rest of the project will be created, and the template is going to be documented with a [wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Issue-Template) which is going to be found on the sidebar under the communication plan. Actually, this issue is also written according to the new template.

The description, reviewer or reviewers,  task deadline, and review deadline should be indicated clearly in the issue. However, adding todo or todo's is optional. They can be added to the issue as below if needed.

***Todo*:**
- [x] Create [Issue Template Wiki Page](https://github.com/bounswe/bounswe2022group5/wiki/Issue-Template).

**Reviewer:** @Keremgunduz7 

**Task Deadline:** 10.10.2022 14:00
**Review Deadline:** 10.10.2022 19:00

**Comment by yavuuzsameet** [comment]
Issue Template is added to the related wiki page, and placed on the sidebar. Additions or changes may occur due to requests and reviews.

**Comment by canberkboun9** [comment]
Hey, should we use *Italics* like you showed in the page?

**Comment by yavuuzsameet** [comment]
I think there is a conflict about that, we can discuss what should we do in the future issues in the next meeting. Keep it as it is for now.

**Comment by canberkboun9** [comment]
How about this?

We would use Italics in only title parts: Description, Todo, Reviewer, Deadline... But texts after ":" would be normal.

**Comment by yavuuzsameet** [comment]
Okay, I am changing the template as requested.

**Comment by Keremgunduz7** [comment]
This looks good to me. For now we can close the issue. In further needs, this issue can be reopened.

Great work, thanks a lot to your efforts.

**Comment by canberkboun9** [comment]
Reopening the issue.

I think we should add a part to *Description*. There should be a mention to which task this issue is connected. 
For example: 

***Description*:**

Task 8 - [Meeting 13.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-13.1)
description of the issue.

**Comment by canberkboun9** [comment]
People who want to put this part into the *Description* may put it. We came on the conclusion that it is not a must have. Closing the issue again
