### ISSUE TITLE
Creating a wiki page for Git and GitHub research

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#17]
Research about how to use Git and GitHub and the differences between the two is made. I took the responsibility to edit the [wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Git-and-GitHub) with the inputs coming from teammates.

**Comment by Keremgunduz7** [comment]
### Suggestion:
[Introduction to Github APIs](https://www.loginradius.com/blog/async/github-api/)
and afterwards,
[Useful git Commands List](https://www.loginradius.com/blog/async/git-commands/)

**Comment by mehmetemreakbulut** [comment]
Hey @yavuuzsameet, This [link](https://towardsdatascience.com/what-is-git-and-why-is-it-so-important-dce559b27833) is very useful to understand why Git is so important. You can add it to the page.

**Comment by yavuuzsameet** [comment]
I added Need Review status to the issue, after reviewing I will close the issue within a day.

**Comment by mehmetemreakbulut** [comment]
> I added Need Review status to the issue, after reviewing I will close the issue within a day.
I reviewed the page. Classification is very successful to distinguish the differences of the links. New links can easily be added to the page.

**Comment by oguzhandemirelx** [comment]
Suggestion:
[Git vs. GitHub: What's the difference?](https://www.youtube.com/watch?v=wpISo9TNjfU)

**Comment by yavuuzsameet** [comment]
> Suggestion: [Git vs. GitHub: What's the difference?](https://www.youtube.com/watch?v=wpISo9TNjfU)

Done.

**Comment by yavuuzsameet** [comment]
Enough link is collected, closing the issue.
