### ISSUE TITLE
Updating Communication Plan, and its Wiki Page.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#174]
**Description:**

* Updating Communication Plan, and its Wiki Page. Making Arrangements to the upcoming meetings. *

***Todo's*:**
- [x] *Updating Communication Plan, and its Wiki Page*.
- [x] *Sending a poll to acquire eligible meeting times*.

**Reviewer:** @mehmetemreakbulut 
**Task Deadline:** 10.10.2022 14:00
**Review Deadline:** 10.10.2022 19:00

**Comment by Keremgunduz7** [comment]
- Opened poll and sent to all teammates https://www.when2meet.com/?17204117-QASlb

- Updated [communication plan wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page)

Note that, weekly meeting times are subject to change.

@mehmetemreakbulut could you please review the table on [communication plan wiki page](https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page).

**Comment by mehmetemreakbulut** [comment]
Pool is very useful to determine the meeting dates. Communication plan seems well. Closing issue

**Comment by canberkboun9** [comment]
We could add routine meeting in the LAB every Tuesday at 15:00.

**Comment by Keremgunduz7** [comment]
Thanks for the review, changes applied.

Closing the issue.
