### ISSUE TITLE
Updating the Project Plan and RAM according to the Meeting 14.1

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#177]
***Description*:**

Roles were distributed and teams were formed in the [Meeting 14.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-14.1). These teams are different than our teams in [Project Plan](https://github.com/bounswe/bounswe2022group5/wiki/Project-Plan) and [RAM](https://github.com/bounswe/bounswe2022group5/wiki/RAM) in the Milestone 2. These files and plans are need to be updated according to the decisions made in the meeting.

***Todo's*:**
- [x] Updating the [Project Plan](https://github.com/bounswe/bounswe2022group5/wiki/Project-Plan).
- [x] Updating the [RAM](https://github.com/bounswe/bounswe2022group5/wiki/RAM).

***Reviewer*:** @kardelendemiral 

***Task Deadline*:** 18.10.2022 22:00
***Review Deadline*:** 19.10.2022 22:00

**Comment by canberkboun9** [comment]
Taking the conversation with the assistant into consideration about detailing the project plan besides updating team members in the plan, I think I need to wait until we prepare a solid plan and specify some details.
Also, I think someone can help me in the process.
So, deadline is TBD.

**Comment by canberkboun9** [comment]
- Project Plan is updated and the [Project Plan Page](https://github.com/bounswe/bounswe2022group5/wiki/Project-Plan) is updated as well.

**Comment by canberkboun9** [comment]
- RAM is updated and [RAM Page](https://github.com/bounswe/bounswe2022group5/wiki/RAM) is updated as well.

**Comment by kardelendemiral** [comment]
Thank you Canberk! Now that both Project Plan and the RAM is updated, we can close this issue.
