### ISSUE TITLE
Revising the Use Case Diagram

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#178]
***Description*:**

Some changes are discussed to be made on [Project Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements). The task is to revise the [Use Case Diagram](https://github.com/bounswe/bounswe2022group5/wiki/Use-Case-Diagram), and make adjustments needed according to the modifications done in the requirements.

***Todo's*:**
- [x] Update the Use Case Diagram.
- [x] Upload the new version to the repository.

***Reviewers*:** @palahb, @oguzhandemirelx  

***Task Deadline*:** 17.10.2022 23:00  
***Review Deadline*:** 18.10.2022 12:00

**Comment by yavuuzsameet** [comment]
We have altered the Use Case Diagram in a small meeting. What we have done is as follows:
- Added *View Activity History* as an extension to the *View Profile*.
- Moved *Edit Own Article* and *Delete Own Article* from Registered Users to Doctors.
- Chatbot is changed, *Ask Question* and *Get Suggestion* blocks are removed, and *Chatbot Decision Tree* is added.
- *Phone Number Confirmation* is deleted from *Sign Up* inclusions.
- *Sign In with Phone Number* is deleted from *Sign In* extensions.
- *Propose Article* is removed from Member attributes.
- *Approve Article* is removed from Doctor attributes.

The new Use Case Diagram can be found on [its page](https://github.com/bounswe/bounswe2022group5/wiki/Use-Case-Diagram).

It can be now reviewed.

**Comment by Keremgunduz7** [comment]
New file as image uploaded to the [Use Case Diagram] (https://github.com/bounswe/bounswe2022group5/wiki/Use-Case-Diagram) page.
Thanks in advance to the reviewers and @yavuuzsameet for the efforts.

**Comment by palahb** [comment]
I think this updated version successfully reflects the changes we have decided. Thank you for all your efforts. After @oguzhandemirelx's review, we can close the issue.

**Comment by oguzhandemirelx** [comment]
It looks good to me, thanks for your effort.
