### ISSUE TITLE
Editing the Meeting Notes Template according to the feedback in the lecture on 08.03.2022

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#18]
Action Items need to have deadlines and/or reviewers.

**Comment by palahb** [comment]
Also, action items need to be enumerated.

**Comment by canberkboun9** [comment]
We could put time limitation to our meetings. It could increase productivity.

**Comment by canberkboun9** [comment]
> We could put time limitation to our meetings. It could increase productivity.

Added the "duration".  
I will close this issue as the group reviewed it in the meeting and it can be said that this is the final version of the [Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template).
