### ISSUE TITLE
Revising the Scenarios and Mockups, make adjustments needed according to the changes done in the Requirements.

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#182]
***Description*:**

There are some changes in the [Project Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements) after [Meeting 14.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-14.1). The task is to revise the [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1),[Scenario 2](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-2),[Scenario 3](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-3) , and make adjustments needed according to the modifications done in the requirements.

***Todo's*:**
- [x] Revising Scenario and Mockups and comparing them with [Project Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements).
- [x] Updating the Scenarios and Mockups if the changes affect them.

***Reviewers*:** @yavuuzsameet , @Keremgunduz7 

***Task Deadline*:** 17.10.2022 23:00  
***Review Deadline*:** 18.10.2022 12:00

**Comment by mehmetemreakbulut** [comment]
The requirements were re-examined in their modified form. Since we did not make any significant changes on the requirements, scenarios and mockups were not affected by this situation. The scenarios and mockups that I have revised last week are at a usable level. Need review

**Comment by yavuuzsameet** [comment]
In [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1): 
The acceptance criteria should be updated. We do not have a phone number utility at the moment.
- 1.1.1.2.1 Members shall be able to sign in to the system using their nickname, e-mail or phone number, and their password.

In [Scenario 2](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-2):
Same as above. 
- 1.1.1.2.2 Doctors shall be able to sign in to the system using an e-mail or phone number and their password.

In [Scenario 3](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-3):
Same as above. 
- 1.1.1.2.1: Members shall be able to sign in to the system using their nickname, e-mail or phone number, and their password.

**Comment by Keremgunduz7** [comment]
Maybe we can check for the requirements again, especially related with the phone number requirements.
In example, [Sign Up Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1111-sign-up) had phone number validations before, and they are used in some of the scenarios.

But,
Overall LGTM for me too at least for now. It can be usable but improvable also.

**Comment by mehmetemreakbulut** [comment]
I changed the acceptance criteria with respect to your reviews. I changed the criteria for sign-in. Thanks. After your final review, we can close the issue.

**Comment by yavuuzsameet** [comment]
Thanks for the update, looks okay now.

**Comment by Keremgunduz7** [comment]
Sorry for my late response. 
Thanks for all the efforts @mehmetemreakbulut .
Closing the issue now.
