### ISSUE TITLE
Deciding on Time and Platform for Backend Team First Meeting

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#183]
***Description*:**

As Backend Team (@mehmetemreakbulut , @canberkboun9 , @irfanbozkurt , @oguzhandemirelx), we need to decide the first meeting time and platform. Also, an agenda is crucial for a productive meeting. 
Agenda determined during the [Meeting 15.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-15.1):
* Deciding on the table structure of the database (decided as PostgreSQL)
* Getting familiar with other technologies we would use
* Determining communication plan for the backend team
* Creating an initial project (decided as Python/Django)

***Todo's*:**
- [x] Deciding on the time and platform for the backend team.

***Reviewers*:** @canberkboun9 , @irfanbozkurt , @oguzhandemirelx 

***Task Deadline*:** 20.10.2022 23:00  
***Review Deadline*:** 21.10.2022 12:00

**Comment by mehmetemreakbulut** [comment]
By talking on Discord, we decided that our first meeting will be on 20.10.2022 at 23.00 on Discord. We will talk about the backend next steps by developing the above agenda.

**Comment by canberkboun9** [comment]
Let's meet!
