### ISSUE TITLE
Preparing the Pull Request Template

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#184]
***Description*:**

Having a single format for pull requests is very important for readability and seeing changes. For this reason, it is necessary to prepare a common pull request template. A template should be prepared by examining different repositories and looking at best practices on the internet.

***Todo's*:**
- [x] Searching for PR Examples on GitHub and other websites.
- [x] Preparing the Pull Request Template.

***Reviewers*:** @yavuuzsameet 

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25.10.2022 12:00

**Comment by mehmetemreakbulut** [comment]
* [Pull Request Template](https://github.com/bounswe/bounswe2022group5/wiki/Pull-Request-Template) is done.

**Comment by oguzhandemirelx** [comment]
I made some improvements about the pull request template. Added more explanation to the fields and we have a new field, Title.

**Comment by Keremgunduz7** [comment]
Maybe we can have a naming convention for PR's also. Like:
Starting with a tag in a square brackets.
[Frontend] For the Frontend Developments PRs,
[Mobile] For the Mobile development PRs,
[Backend] For the Developments made on backend side.

Such as:
[Frontend] Added Login Button to the Homepage layout.

**Comment by mehmetemreakbulut** [comment]
- Thanks @oguzhandemirelx, @Keremgunduz7's suggestions were applied. We can close the issue now.
