### ISSUE TITLE
Logo and Name Suggestions

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#185]
***Description*:**

As we proceed with the project, we need a good-looking and also meaningful logo, and a name too. The suggestions are expected to be commented on this issue. 

What should be the name of the project and the logo?

***Reviewer*:** @Keremgunduz7  

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25/10/2022 12:00

**Comment by palahb** [comment]
For the name, what about **hiqmed**? It sounds like the Turkish word "_hikmet_" which means _wisdom_. May sound a bit weird though :)

**Comment by palahb** [comment]
I came up with other names but they are currently in use by other applications or institutions in the web:
- medhub
- medichub
- healthub
- medlink
- mednet
- medly
- aide

**Comment by canberkboun9** [comment]
I can put my two cents:
- GetMedInfo
- ClinicalWeb
- AppleADay
- Sun in the House M.D.

**Comment by Keremgunduz7** [comment]
I liked @bbenginbestas 's idea. My vote is also for the Hippocrates.

**Comment by yavuuzsameet** [comment]
I am also fancying Hippocrates at the minute.

**Comment by palahb** [comment]
What if we simplify it a bit and say __Hipocrat__?

**Comment by bbenginbestas** [comment]
If we choose 'Hippocrates' or something similar to that, maybe the logo can be a cute hippo?

**Comment by canberkboun9** [comment]
> If we choose 'Hippocrates' or something similar to that, maybe the logo can be a cute hippo with a stethoscope or something?

Kawai idea!

**Comment by canberkboun9** [comment]
I have a logo suggestion:

![hippo](https://user-images.githubusercontent.com/47902320/198892280-78cf2a78-d2fc-4081-82c9-a7ad87237dff.jpg)

**Comment by oguzhandemirelx** [comment]
@canberkboun9 i loved your suggestion. Hippocrates name can be so good with this logo!

**Comment by bbenginbestas** [comment]
@canberkboun9 Looks perfect, great job! Can we make it a bit simpler? It looks so detailed for an app i think

**Comment by mehmetemreakbulut** [comment]
Good suggestions. I think we can close the issue and can analyze the suggestions at the meeting.
@Keremgunduz7

**Comment by Keremgunduz7** [comment]
I think that also, it seems that we have decided on the name as "Hippocrates" . We can also review it in the meeting which is the one that take place in the labs.
I have also loved the suggestion of @canberkboun9 . We can also discuss further for the logo in the meeting. But I think that the suggestions are ended for now for the logo and names.
Thanks a lot to all teammates for the suggestions and, @yavuuzsameet for creating the issue and starting the discussion.
Closing the issue. But, it is just for now, feel free to reopen it whenever you have another suggestion or an opinion.
