### ISSUE TITLE
Adding New Labels to Distinguish Issues for Different Groups' Tasks

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#186]
***Description*:**

Project development takes a new level now and we are starting the implementation. Our label set was in a good shape. However, it need some improvement. 
- We need new issues for backend, frontend, and mobile team accordingly. 
- Also, some labels may need abbreviation/shortening. 

***Todo's*:**
- [x] Creating new issues: backend, frontend, mobile.
- [x] Revising/editing some of the labels accordingly.

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 23.10.2022 22:00  
***Review Deadline*:** 24/10/2022 22:00

**Comment by canberkboun9** [comment]
I made some changes to some labels. Added labels for team. My thought is: 
- Should we make these changes:
- Priority => Prio and Prio: Medium, Prio: Low, etc. 
- The reason is that labels are ordered alphabetically next to the issue title.
- This would solve the issue. 
- Likewise, the same change may be applied to the teams:
- Team: Backend, Team: Frontend, Team: Mobile.

**Comment by canberkboun9** [comment]
I made the changes, deleted the "enhancement" label, it was a duplicate.

**Comment by mehmetemreakbulut** [comment]
The labels seem okay. We can close the issue

**Comment by canberkboun9** [comment]
The changes as a list: 
- Changed/added descriptions and colors of some labels: 
- Added Team labels; Team: Backend, Frontend, Mobile
- Deleted enhancement label, it was a duplicate.
- Put the Priority before the High, Medium etc. to achieve order of labels. Also, made it Prio to be short.
