### ISSUE TITLE
Pushing initial backend project to GitHub

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#187]
***Description*:**

As a backend team, we discussed the initial steps of the development process. In the [meeting](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.1) we determined the generic structure of the project. Also,  a new backend branch is needed for the development process.
***Todo's*:**
- [x] Setting up initial Django project.
- [ ] Creating a backend branch and pushing the project.

***Reviewers*:** @irfanbozkurt 

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25.10.2022 12:00

**Comment by irfanbozkurt** [comment]
Hey all!

We later decided to keep everything at one master branch.

I think we should rather create a "develop" branch for every team to use, but this is not a task for now. I'll remind this "GitFlow" issue to the team after the customer meeting.

Thanks for staying in tune!
