### ISSUE TITLE
Research about the W3C Web Annotation Data Model

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#19]
#### Description:
Research about the W3C Web Annotation Data Model and W3C standards for our Medical Experience Sharing Platform Project. We will also write a short description of our research.

#### Reviewers:
@mehmetemreakbulut, @burakmert236

**Comment by palahb** [comment]
Some information is added to the corresponding section in the [Research](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project) page. Needs to be improved by additional information.

**Comment by oguzhandemirelx** [comment]
I added some additional information about Annotation Data Model.

**Comment by burakmert236** [comment]
I think you have gathered great information about this topic to fill our requirements file, we may continue to research when we get to work with our project and need more information about the related topic.

**Comment by mehmetemreakbulut** [comment]
I have reviewed the issue. The research is helpful to understand W3C Web Annotation Data Model. After @burakmert236's review, we can close the issue.

**Comment by palahb** [comment]
By cosidering @burakmert236's above comment about our research, I think we can close the issue. If more information is needed, we can reopen this issue. Thanks for your contributions.
