### ISSUE TITLE
Creating a Sign-up Screen - Mobile

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#193]
***Description*:**

A sign-up screen where a user can enter the required information for sign-up will be created for the mobile application. 

***Todo's*:**
- [ ] Mobile sign-up screen will be created.

***Reviewers*:** @palahb 

***Task Deadline*:** 25.10.2022 10:00  
***Review Deadline*:** 25.10.2022 12:00

**Comment by palahb** [comment]
Necessary screens are successfully created by @kardelendemiral. Later, some minor changes may be needed. Thank you Kardelen!
