### ISSUE TITLE
Creating requirements.txt for backend development

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#195]
***Description*:**
- Requirements.txt is required for the development process for backend developers to check dependencies and work in harmony.
- For this reason, it is important to update the requirements whenever a new package is used.
- 

***Todo's*:**
- [x] Run the command pip freeze > requirements.txt.
- [x] Push project to the repository

***Reviewer*:** @canberkboun9  

***Task Deadline*:** 24/10/2022 23:00
***Review Deadline*:** 25/10/2022 12:00

**Comment by canberkboun9** [comment]
I merged the branch to check the file. I got errors and found solutions.
If you are using Python3.9+, you get errors. So we need to change the Requirements.txt file. 
- We need to change " backports.zoneinfo==0.2.1 " line with " backports.zoneinfo==0.2.1;python_version<"3.9" "

Can you make the change and open another pull request again, please?

**Comment by mehmetemreakbulut** [comment]
- Changes were made we can close the issue

**Comment by canberkboun9** [comment]
I saw the changes were done under the [PR 219](https://github.com/bounswe/bounswe2022group5/pull/219/commits/0de5ac87bfc8a33df15f6c9a38ec87f61af70492). Thanks!

**Comment by mehmetemreakbulut** [comment]
> I saw the changes were done under the [PR 219](https://github.com/bounswe/bounswe2022group5/pull/219/commits/0de5ac87bfc8a33df15f6c9a38ec87f61af70492). Then, the changes deleted in [PR 231](https://github.com/bounswe/bounswe2022group5/pull/231). Now, when I try to use "pip install -r requirements.txt" command in my terminal the error occurs again. But, when I change the line 2 as
> 
> backports.zoneinfo==0.2.1;python_version<"3.9"
> 
> it works correctly. So, we need this part in the requirements, I think.

For deployment, the requirements.txt file works well with this version. This issue is solved now. I think we can close the issue if you agree with me.

**Comment by canberkboun9** [comment]
Yes, we can discuss it later as it doesn't pose a difficulty or danger. It can be closed now.
