### ISSUE TITLE
Connecting DB Engine to Django app

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#197]
***Description*:**

Task 3 - [Backend Meeting 1.1](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.1) 
DB is created [Issue #194](https://github.com/bounswe/bounswe2022group5/issues/194). I need to connect it to the app.

***Todo's*:**
- [X] Connecting DB Engine to Django app

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25/10/2022 12:00

**Comment by mehmetemreakbulut** [comment]
* Everything is implemented as we mentioned in [Backend Meeting 1.1](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.1) 
* Working with a remote database can help us to work synchronously. 
* After the creation of initial user tables we can start to implement some basic auth configurations and endpoints.
