### ISSUE TITLE
Creating Pages for the First Meeting Notes and the Meeting Notes Template on Wiki

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#2]
### Description:
I have opened a [codeshare page](https://codeshare.io/) before the [Meeting 1.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-1.1), and designed a baseline for the Meeting Notes Template. During the meeting, filled this meeting note with the team. 
### To Do:

- [X] This meeting notes will be uploaded into a page. 
- [X] The page should be under a page containing other meeting notes, so this will be created.
- [X] Meeting Notes Template will be reviewed and designed again and added as a page.

**Comment by canberkboun9** [comment]
Leaving open for reviews.
Also: I couldn't organize the pages created on the site of the wiki page. I will research about it.

**Comment by canberkboun9** [comment]
> Leaving open for reviews. Also: I couldn't organize the pages created on the site of the wiki page. I will research about it.

[My comment](https://github.com/bounswe/bounswe2022group5/issues/13#issuecomment-1060044906) in Issue #13 mentions the solution for organizing the meeting notes.

**Comment by canberkboun9** [comment]
Reviewed the [Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template). Edited it a little.
Emre had already put the page as anchor text on the sidebar. I reviewed the Sidebar and changed the page's name.

**Comment by mehmetemreakbulut** [comment]
I reviewed the First Meeting Notes and the Meeting Notes Template. I think we can close the issue.
