### ISSUE TITLE
Creating a new wiki page for gathering research items for project and its description

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#20]
Description:

A wiki page will created for the sake of gathering some research items related to the project and project description. Some of major research topics are W3C Web Annotation Data Model, Telegram’s Chatbot API and DBPedia Medical Onthology.

Reviewers:

@kardelendemiral, @Keremgunduz7 

Task Deadline: 12.03.2022 - 20:00
Review Deadline: 12.03.2022 - 13:00

**Comment by burakmert236** [comment]
Added a wiki page for the research results. Researchers can add their research items to [this page](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project).

**Comment by canberkboun9** [comment]
Seems nice to me but additional review is needed.

**Comment by Keremgunduz7** [comment]
The page looks great. Thanks for your effort @burakmert236 .
As a suggestion maybe you can edit the page in terms of ordering the contents in an alphabetic order after all research is completed for this week. In the near future, maybe we may have more contents, in that case an ordering might be helpful.

**Comment by burakmert236** [comment]
I changed the wiki page to make current content in alphabetical order. Researchers can add their research items to the page in this order from now. Since this issue accomplished its goal, I am closing it.
