### ISSUE TITLE
Deciding on Meeting Time and Platform for Backend Team

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#200]
***Description*:**

Task 11 - [Backend Meeting 1.1](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.1) 
Backend Team meetings will occur regularly. Meeting time needs to be decided upon. (We meet occasionally out of this decision, but their meeting notes will be uploaded as well.)

***Todo's*:**
- [x] Creating and sending a link to the backend team.
- [ ] Edit the Communication Plan page accordingly.

***Reviewer*:** @oguzhandemirelx 

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25/10/2022 12:00

**Comment by canberkboun9** [comment]
Platform is definitely Discord, no doubt. Can you fill the table above, please? @mehmetemreakbulut @irfanbozkurt

**Comment by mehmetemreakbulut** [comment]
As we see from the table, it will be convenient for everyone to hold a meeting at 22:00 Thursday. We can close the issue now.

**Comment by irfanbozkurt** [comment]
@canberkboun9 done!
