### ISSUE TITLE
Creating API documentation for Login

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#201]
***Description*:**

Task  8 - [Backend Meeting 1.1](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.1) 
We plan to create API documentations before implementation. We will use swagger. But further discussion is needed about the details.

***Todo's*:**
- [ ] Creating the API documentation for Login.

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25/10/2022 12:00

**Comment by canberkboun9** [comment]
- An inital [Login Documentation Page](https://github.com/bounswe/bounswe2022group5/wiki/Login-API-Documentation) has been created.
- API documentation added to Wiki sidebar.
- Need Review @mehmetemreakbulut

**Comment by mehmetemreakbulut** [comment]
I have arranged some fields. Now, it is done. Thank you for your effort!

**Comment by canberkboun9** [comment]
-I changed the token part according to REST framework documentation.
