### ISSUE TITLE
Creating the API documentation for Signup

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#206]
***Description*:**

Task  7 - [Backend Meeting 1.1](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.1) 
We plan to create API documentation before implementation. We will use swagger. But the further discussion is needed about the details. 

***Todo's*:**
- [x] Creating the API documentation for Signup.

***Reviewer*:** @canberkboun9 

***Task Deadline*:** 24.10.2022 23:00  
***Review Deadline*:** 25/10/2022 12:00

**Comment by mehmetemreakbulut** [comment]
- [Signup Documentation Page](https://github.com/bounswe/bounswe2022group5/wiki/Signup-API-Documentation) has been created. 
- API documentation added to Wiki sidebar.

**Comment by canberkboun9** [comment]
Thank you Emre, it's well constructed and readable. We can close the issue.
