### ISSUE TITLE
Font Suggestions

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#209]
***Description*:** 

Fonts we will be using in our applications should be determined. Therefore, fonts that can be used will be suggested under this issue. Members can contribute and give feedback about fonts suggested.

Which font/fonts should we use?

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 24/10/2022 23:00
***Review Deadline*:** 25/10/2022 12:00

**Comment by enginoguzhansenol** [comment]
After the discussion in the meeting, we will decide the fonts that are going to use in our app after Milestone 1. Closing the issue now, it may be opened later.
