### ISSUE TITLE
Opening a wiki page for the Tech Stack

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#210]
**Description:**

* Creating a wiki page that lists the technologies we will use in the project

***Todo's*:**
- [x] *Creating a wiki page of technologies we will use*

**Reviewer:** *@canberkboun9* 

**Task Deadline:** 25.10.2022 10:00  
**Review Deadline:** 25.10.2022 12:00

**Comment by mehmetemreakbulut** [comment]
* Wiki page has been opened. Tech stack is available on the [page](https://github.com/bounswe/bounswe2022group5/wiki/Tech-Stack).

**Comment by canberkboun9** [comment]
- It can be tabularized, it may look better. 
- You realized during the meeting that for the dark background there is a problem, I cannot see it as I use dark background and was sharing my screen. 
- It has all the tools we use for now.

**Comment by mehmetemreakbulut** [comment]
> * It can be tabularized, it may look better.
> * You realized during the meeting that for the dark background there is a problem, I cannot see it as I use dark background and was sharing my screen.
> * It has all the tools we use for now.

- Tabularizing doesn't work well with tech stack page. Images is really powerful to demonstrate tech stack.
- Backgrounds fixed

**Comment by canberkboun9** [comment]
Checked the last version, it looks great! Closing the issue.
