### ISSUE TITLE
Adding user type selection for Signup - Mobile

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#216]
***Description*:**

As discussed in the [Meeting 16.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-16.1), it was required adding a user type selection to the sign-up screen and showing the required fields for sign-up according to the selected user type. 

***Todo's*:**
- [x] User type selection will be added to the sign-up form.

***Reviewer*:** @palahb 

***Task Deadline*:** 29/10/2022 23:00 
***Review Deadline*:** 30/10/2022 12:00

**Comment by kardelendemiral** [comment]
Adding this feature, I opened the [pull request #215 ](https://github.com/bounswe/bounswe2022group5/pull/215) and added this feature also. We will discuss the alignment of sign-up form with the frontend team and I will be making some other modifications for that purpose. If required, new issue will be opened.

**Comment by palahb** [comment]
As you have already implemented this feature, we can close the issue. Other improvements can be discussed in the following issues. Thank you!
