### ISSUE TITLE
Changing Requirements w.r.t Meeting 16.1 Discussion

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#217]
**Description:**

*Requirements need to be changed after [Meeting 16.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-16.1).*

***Todo's*:**
- [x] *Editing requirements*

**Reviewer:** *@bbenginbestas * 

**Task Deadline:** 26.10.2022 23:00  
**Review Deadline:** 27.10.2022 12:00

**Comment by enginoguzhansenol** [comment]
According to  [Meeting 16.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-16.1) Discussion, certain changes have been made to the Requirements. There are requirements that are removed, changed, or newly added. The edited requirements are can be listed below:
### Removed
* **1.1.1.1.3** Members shall prove that they are a real person with authentication while registering.
* **1.1.1.1.13** Registered users shall be able to make their personal information public/private/protected while registering.* * **1.1.1.1.10** Registered users shall be able to register their medical history to the system while registering.
* **1.1.1.1.11** Doctors should be able to provide a profile picture while registering.
* **1.1.1.1.12** Doctors should be able to provide a profile picture while registering.
* **1.1.1.3.5** Registered users shall have their posts visible in their profiles.
* **1.1.1.4.6** Registered users shall be able to make their personal information public/private/protected.

### Added
* **1.1.1.1.6** Registered users shall confirm their password while registering.

### Changed

* **1.1.1.1.4** Doctors shall provide their real name.
**1.1.1.1.3** Doctors shall provide their full name.
* **1.1.1.1.14** Doctors shall provide categories that they are specialized while registering.
**1.1.1.1.10** Doctors shall provide branches that they are specialized while registering.
* **1.1.1.2.1** Members shall be able to sign-in to the system using their e-mail and their password.
**1.1.1.2.1** Members shall be able to sign-in to the system using their username or e-mail and their password.
* **1.1.1.3.6** Doctors and registered users shall be able to see only their own activity history in their profile pages.
**1.1.1.3.5** Registered users shall be able to see the activity histories in profile pages.

Need a review of @bbenginbestas.

**Comment by bbenginbestas** [comment]
The amount of work done for the task is obvious. It looks great. Closing the issue now.
