### ISSUE TITLE
Research about Ontologies, Medical Ontologies and DBPedia

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#22]
**To Do:**

- A research will be made about medical ontologies and DBPedia to get the idea of how to use these in our Medical Experience Sharing Platform Project.
- Information about these items will be added to our [Research Items for Project](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project) page.

**Reviewers:**
@palahb ,  @bbenginbestas 

**Task Deadline:** 14.03.2022 - 13:00 GMT+3
**Review Deadline:** 14.03.2022 - 20:00 GMT+3

**Comment by kardelendemiral** [comment]
Added the definition of ontologies and medical ontologies. Also added a small image to give an idea what a medical ontology is. 

**To do:** Information about DBPedia will be added.

**Comment by busetolunay** [comment]
Information about DBPedia and a linked data diagram is added to the wikipage.

**Comment by kardelendemiral** [comment]
We can reopen the issue if we need to add additional information.  Closing the issue.
