### ISSUE TITLE
Creating Forum page - Frontend

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/bounswe2022group5#223]
***Description*:**
- Forum part of the page will be created. Posts with details should be coded as described at https://www.figma.com/file/c9akZ5H2c2KvrycxlgH8wu/CMPE352?node-id=0%3A1. 

***Tasks Done*:**
- [x] Designs and layouts are implemented for posts and forum.

***Reviewer*:**
  @yavuuzsameet

Task Deadline: 30.10.2022 23:00
Review Deadline: 31.10.2022 12:00

**Comment by yavuuzsameet** [comment]
The related PR is merged. Please link the related pull requests and issues next time so that the issue closes automatically.
