### ISSUE TITLE
Creating mobile login page

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#225]
***Description*:**

Mobile login page will be created.

***Todo's*:**
- [x] Design of the mobile login page.
- [x] Syncronizing the page with other teams

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 27.10.2022 21:00  
***Review Deadline*:** 27.10.2022 22:00

**Comment by enginoguzhansenol** [comment]
I tested the code. The created login page for mobile is very well designed. The login screen can easily be connected to other pages. Great work! Thank you for your collaboration. Merging the request.
