### ISSUE TITLE
Communication Plan for Mobile Team

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#227]
***Description*:**

There is a need for a communication plan for mobile team. There will be a time for regular, and we will talk further each week via communication platforms to change the time when necessary.

***Todo's*:**
- [x] Finding a time that is available for everyone on mobile team.

***Reviewer*:** @palahb 

***Task Deadline*:** 30.10.2022 18:00  
***Review Deadline*:** 30.10.2022 23:59

**Comment by bbenginbestas** [comment]
The time is decided. It is flexible, but intended to be done at Saturday, 18.00.

**Comment by bbenginbestas** [comment]
Communication plan is added to the [Communication Plan](https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page)

**Comment by palahb** [comment]
It seems OK. Thank you Bengin!
