### ISSUE TITLE
Research about Telegram’s Chatbot API

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#23]
To Do:

- Research will be made about Telegram's Chatbot API to get the idea of how to use the bot in our Medical Experience Sharing Platform Project, and the advantages of the Chatbot API.
- Information about the research will be documented in our [Research Items for Project](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project) page.

Reviewers:
@Keremgunduz7 and @makifyilmaz 

Task Deadline: 14.03.2022 - 13:00 GMT+3

**Comment by yavuuzsameet** [comment]
The pros and cons of Chatbots are documented.

**Comment by mehmetemreakbulut** [comment]
Information about Telegram's Chatbot API is added

**Comment by mehmetemreakbulut** [comment]
Some repositories that use Chatbot API are added to the page.

**Comment by Keremgunduz7** [comment]
they seem very understandable and helpful. Thanks for your researches and documentation. After @makifyilmaz 's review, we may close the issue.

**Comment by makifyilmaz** [comment]
I agree with @Keremgunduz7 . The research summarizes the topic very well. Thanks for your efforts. We can close the issue.
The research result can be accessed [here](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project#telegrams-chatbot-api).
