### ISSUE TITLE
Deciding branch convention

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#232]
***Description*:**

A branching strategy is a set of rules, a convention that helps teams and developers. They can follow these rules and conventions to create a new branch. We have to decide a convention to use them.

***Todo's*:**
- [x] Deciding Branch Convention

***Reviewer*:** @bbenginbestas 

***Task Deadline*:** 28.10.2022 18:00  
***Review Deadline*:** 28.10.2022 23:59

**Comment by oguzhandemirelx** [comment]
I created branch convention page and added to the sidebar.
If you review @bbenginbestas, we can close the issue.

**Comment by mehmetemreakbulut** [comment]
Great job Oguzhan. The page is available [here](https://github.com/bounswe/bounswe2022group5/wiki/Branch-Convention).
