### ISSUE TITLE
Editing the README file for mobile development

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#234]
***Description*:**

As discussed in the [Mobile Meeting 2](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-2), the [REAME file](https://github.com/bounswe/bounswe2022group5/tree/master/app/mobile/bounswe5_mobile) for the mobile application will be edited.

***Todo's*:**
- [x] A description of the application will be added.
- [x] A guide about how to run the code will be added.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 31/10/2022 15:00
***Review Deadline*:** 31/10/2022 20:00

**Comment by kardelendemiral** [comment]
I edited the README file adding the necessary information. See: [README](https://github.com/bounswe/bounswe2022group5/tree/master/app/mobile/bounswe5_mobile).
I need review @enginoguzhansenol

**Comment by enginoguzhansenol** [comment]
The readme file explains how we can run the code using the command line, as well as the necessary applications to run the code. It looks self-explanatory and informative. Thanks for your effort. Closing the issue.
