### ISSUE TITLE
Editing the README file of the Backend part of the Project

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#237]
***Description*:**

The README file is a necessity for the project documentation. Assuming a new member joined the team, the README file is one of the most essential part for them to start learning about the project.
 [README file](https://github.com/bounswe/bounswe2022group5/blob/master/app/backend/README.md) for the backend application needs to be edited accordingly.

***Todo's*:**
- [x] Brief description of the application's backend part needs to be added.
- [x] Guide about how to run the code needs to be added.

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 31/10/2022 19:00
***Review Deadline*:** 31/10/2022 23:00

**Comment by irfanbozkurt** [comment]
Let's not forget "how to run locally", "how to dockerize", and "how to run as a docker container" sections; just as a series of commands.

Thanks!

**Comment by canberkboun9** [comment]
- I filled the [README.md](https://github.com/bounswe/bounswe2022group5/blob/master/app/backend/README.md) page. Can you review @mehmetemreakbulut, please

**Comment by mehmetemreakbulut** [comment]
I reviewed the file. Seems very well. We can close the issue.
