### ISSUE TITLE
Research about Requirements Elicitation

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#24]
To Do:

- Research will be made about old repositories to acquire knowledge how to conduct requirements elicitation.
- Information about the research will be documented in our [Research Items for Project](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project) page.

#### Reviewers:
@busetolunay and @yavuuzsameet

#### Review Deadline: 14.03.2022 - 20:00 GMT+3

**Comment by yavuuzsameet** [comment]
Looks like the deadline has arrived, but no work in the [Research Items](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project) page.

**Comment by canberkboun9** [comment]
I was sick, forgot to add the research to the wiki page.

I added 5 elements to the research for requirements.

**Comment by busetolunay** [comment]
Requirements template and useful tips from previous repositories are added to the [Research Items](https://github.com/bounswe/bounswe2022group5/wiki/Research-Items-for-Project) .

**Comment by enginoguzhansenol** [comment]
The issue has been done and reviewed. We can close it.
