### ISSUE TITLE
Handling the register API call for mobile

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#245]
***Description*:**

Now that the API for signup is complete, the API call for signup must be made for mobile application. Also, some comment should be added to the signup screen code.

***Todo's*:**
- [x] API call for signup should be made.
- [x] Some comment should be added to the signup screen code.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 30.10.2022 12:00
***Review Deadline*:** 30.10.2022 23:00

**Comment by kardelendemiral** [comment]
I completed all the tasks required for this issue and opened a [pull request](https://github.com/bounswe/bounswe2022group5/pull/255). We can close this issue after your review and merge @enginoguzhansenol .

**Comment by enginoguzhansenol** [comment]
The code ran successfully with no conflicts. Great work! Merged the pull request. Closing the issue now.
