### ISSUE TITLE
Creating the Wiki Page of Requirements Elicitation of the project

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#25]
To Do:

- A wiki page will be created that will contain the work of Requirements Elicitation of our project.

#### Reviewers:
@burakmert236 and @oguzhandemirelx 

#### Review Deadline: 13.03.2022 - 20:00 GMT+3

**Comment by canberkboun9** [comment]
Created [Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements) wiki page. Added titles, categorized Functional - Non-Functional, and sub categorized them. We could even sub categorize them more.

@Keremgunduz7 and @bbenginbestas, you can fill this page according to the task #7 in [Meeting 2.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-2.1).

**Comment by burakmert236** [comment]
Seems pretty nice but you could also add this file link to our wiki sidebar.

**Comment by makifyilmaz** [comment]
> Seems pretty nice but you could also add this file link to our wiki sidebar.

Added a new section named "Project" to the sidebar and added the [Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements) wiki page under this section.

**Comment by Keremgunduz7** [comment]
Great work. Seems a pretty nice page. It is going to be a lot more easier from now on to categorize the requirements and filling up the page.

**Comment by bbenginbestas** [comment]
Good job. The page looks great. We can improve it even further by using expandable syntax. I will research the syntax.

**Comment by oguzhandemirelx** [comment]
The page design looks very nice, we can easily check requirements from this page. Categorizations are clear and absolutely sufficient.

**Comment by burakmert236** [comment]
The page has an appropriate template and nice looking now. I'm closing the issue, when we complete filling requirements, we may open another issue to improve appearance of the page later.
