### ISSUE TITLE
Requirements Elicitation page requires more than two assignees.

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#26]
Requirements Elicitation page requires too much work to be handled by two assignees. We should discuss this topic in [Meeting 2.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-2.2).

**Comment by Keremgunduz7** [comment]
Agreed. We need to make a good plan in the meeting in terms of the division of the labour.
