### ISSUE TITLE
Documenting Backend code conventions

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#262]
***Description*:**

Coding conventions help the developing team to understand each other's code and communicate ideas. The benefits of these rules can be seen more effectively in a large team. We have 4 people in the backend team. It is not such a big team, but some code convention might be reasonable to have. 

***Todo's*:**
- [x] Create a [page](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Code-Conventions) for the backend code conventions
- [x] Create the conventions, edit the page.

***Reviewer*:** @oguzhandemirelx 

***Task Deadline*:** 30.10.2022 23:00  
***Review Deadline*:** 31.10.2022 23:00

**Comment by canberkboun9** [comment]
- Created the page, and conventions in it. 
- Added it to the Sidebar.

**Comment by oguzhandemirelx** [comment]
Excellent job, Canberk. I think we can add [Error 500 - Internal Server Error] to our error handling part because we will probably encounter them too. Also, we can add comment conventions for the backend team to our page.

**Comment by mehmetemreakbulut** [comment]
Great! Also, we can add code style and conventions from [official Django documentation](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) as a relevant link.

**Comment by canberkboun9** [comment]
> Excellent job, Canberk. I think we can add [Error 500 - Internal Server Error] to our error handling part because we will probably encounter them too. Also, we can add comment conventions for the backend team to our page.

Thanks, I will add the error code. Comments should not be considered as documentation examples, I think. Too much of them and some unnecessary ones make the code cluttered. And the convention should be to write them in the code to translate complex parts. Also, we can use some documentation tools generating documentation from comments over functions etc. I forgot now.

> Great! Also, we can add code style and conventions from [official Django documentation](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) as a relevant link.

Nice suggestion, but, can you add it like in your mind? I don't know which parts to add.

**Comment by mehmetemreakbulut** [comment]
> > Excellent job, Canberk. I think we can add [Error 500 - Internal Server Error] to our error handling part because we will probably encounter them too. Also, we can add comment conventions for the backend team to our page.
> 
> Thanks, I will add the error code. Comments should not be considered as documentation examples, I think. Too much of them and some unnecessary ones make the code cluttered. And the convention should be to write them in the code to translate complex parts. Also, we can use some documentation tools generating documentation from comments over functions etc. I forgot now.
> 
> > Great! Also, we can add code style and conventions from [official Django documentation](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) as a relevant link.
> 
> Nice suggestion, but, can you add it like in your mind? I don't know which parts to add.

Yes, I added the relevant links that we use.

**Comment by canberkboun9** [comment]
I added the comment conventions, I think we can close the issue.

**Comment by oguzhandemirelx** [comment]
Yes, everything looks good. Thanks for your effort.
