### ISSUE TITLE
Documenting Frontend Code Conventions

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/bounswe2022group5#263]
***Description*:**

Coding convention is important for teams. In order to make the code more sustainable and systematical, a document of code convention rules is needed.

***Todo's*:**
- [x] Creating frontend code conventions page.
- [x] Listing the conventions and explaining them.

***Reviewer*:** @Keremgunduz7 

***Task Deadline*:** 30.10.2022 23:30
***Review Deadline*:** 31.10.2022 23:30

**Comment by Oozankilic** [comment]
https://github.com/bounswe/bounswe2022group5/wiki/Frontend-Code-Conventions  Page is create. Conventions are added.

**Comment by Keremgunduz7** [comment]
Thanks a lot for creating the page and filling it with the basic conventions. I think that we are going to add more to these ones. But for now we can close this issue. We can reopen it up whenever a change is needed.
Thank you for the efforts.
