### ISSUE TITLE
[Mobile] Code conventions for Mobile Development

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#264]
***Description*:**

Coding conventions are a set of guidelines for a specific programming language that recommend programming style, practices, and methods for each aspect of a program written in that language. We need code conventions for our mobile team.

***Todo's*:**
- [x] Create a page for the backend code conventions
- [x] Create the conventions, edit the page.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 31.10.2022 20:00  
***Review Deadline*:** 31.10.2022 23:59

**Comment by enginoguzhansenol** [comment]
All types of code conventions seem to be made for the mobile team. It looks excellent. Thanks for your collaboration, closing the issue now.
