### ISSUE TITLE
Creating Scenario 2 for Milestone 1

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#266]
***Description*:**

Task 20 in [Meeting 16.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-16.1)

In the milestone we will do a presentation about the state of our application. We need two scenarios to help us. They are also part of the deliverables. We will work on Scenario 2.

***Todo's*:**
- [x] [Scenario 2 for Milestone 1 page](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-2-for-Milestone-1) will be opened.
- [x] Scenario 2 will be created and mockup screenshots will be added.

***Reviewer*:** @oguzhandemirelx 

***Task Deadline*:** 31/10/2022 19:00
***Review Deadline*:** 31/10/2022 23:00

**Comment by canberkboun9** [comment]
- Except mobile mockup screenshots, all is done.

**Comment by Keremgunduz7** [comment]
Great work done in the meeting. Thanks to all assignees.

**Comment by palahb** [comment]
Mobile screens have been added.

**Comment by oguzhandemirelx** [comment]
Good job @palahb . Mobile screens look excellent. Simple and superior design. We can close this issue, and thanks for your effort.
