### ISSUE TITLE
Creating Scenario 1 for Milestone 1

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#268]
***Description*:**

Task 19 in [Meeting 16.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-16.1).

In the milestone, we will do a presentation about the state of our application. We need two scenarios to help us. They are also part of the deliverables. We will work on [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1-for-Milestone-1).

***Todo's*:**
- [x] [Scenario 1 for Milestone 1 page](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1-for-Milestone-1) will be opened.
- [x] Scenario 1 will be created and mockup screenshots will be added.

***Reviewer*:** @enginoguzhansenol  

***Task Deadline*:** 31/10/2022 19:00
***Review Deadline*:** 31/10/2022 23:00

**Comment by yavuuzsameet** [comment]
@enginoguzhansenol you can check it out, please note that some screenshots are going to be updated in due course.

**Comment by mehmetemreakbulut** [comment]
I have added goal below to scenario:
   * Lucy aims to upvote some articles that she liked.
   
 Need review.

**Comment by palahb** [comment]
I have added mobile screens to the scenario.

I think there is a problem with the frontend screen in the 3rd step, can you check it @yavuuzsameet ?

**Comment by mehmetemreakbulut** [comment]
- I have changed the research fields and branch of the doctor. Ophthalmology is more convenient with the posts on the website.

**Comment by yavuuzsameet** [comment]
> I have added mobile screens to the scenario.
> 
> I think there is a problem with the frontend screen in the 3rd step, can you check it @yavuuzsameet ?

they are going to be updated in due course.

**Comment by enginoguzhansenol** [comment]
It seems that all the items in Scenario 1 are complete. The photos for Mockups looks excellent. Congratulations to each of you for this great teamwork. Closing the issue now.
