### ISSUE TITLE
Categorizing, dividing the requirements into sub-categories.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#27]
We need to divide the requirements to further sub-categories. Thanks to @canberkboun9 who already divided as functional and non-functional parts.

Reviewers: @palahb @canberkboun9

**Comment by canberkboun9** [comment]
We made a review in the meeting and discussed about the structure of the Requirements as a whole in the [Meeting 2.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-2.2). We had some decisions. However, waiting until the lecture and PS may offer some efficiency for us, that is we will take advantage of the new knowledge from these. 

My notes on the Requirements Page for now is: 
- We need to enumerate the requirements' atomic elements, which are the **sentences**. 
- We need to modify the markdown code such that all the sentences have the same **font size** and not be in title font size.
- Subtitles and categorization of the requirements have been reviewed in the meeting and the tasks shared by the team for now. After we have performed some effort for the requirements we will have a meeting on 17.03.2022 - 21:00 GMT+3, which is Meeting 3.1, where we will use our newly acquired knowledge on the topic to edit the Page more effectively.

**Comment by Keremgunduz7** [comment]
We have enumerated all the categories and subcategories.
Whenever and atomic element added, corresponding enumeration should be made.
- Distributed the tasks of the researcing and writing of the requirements category by category.

For now, we can close this issue. Whenever a further categorization needed, this issue can be opened again.

**Comment by Keremgunduz7** [comment]
Closed [#27](https://github.com/bounswe/bounswe2022group5/issues/27)
