### ISSUE TITLE
Communication Plan for Frontend

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/bounswe2022group5#274]
***Description*:**

A communication plan is needed for frontend team. There could be a constant day and hour to meet every week or one day per week according to the workload at that week. The meeting place would be some online communication platform

***Todo's*:**
- [x] Talking with team to determine available meeting times
- [x] Selecting a proper communication platform

***Reviewer*:** @Keremgunduz7 

***Task Deadline*:** 31.10.2022 18:00  
***Review Deadline*:** 31.10.2022 23:59

**Comment by Oozankilic** [comment]
Communication plan is set as every weekend, specific time will be announced according to the week's workload.

**Comment by Oozankilic** [comment]
Communication plan is written to the plan table at: https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page

**Comment by Keremgunduz7** [comment]
Thanks a lot to your efforts and work. It is sufficient to decide on the platform and overall schedule for now.
We can decide on the exact time on every week individually.
Seems look good to me. 
I think we can close the issue if you have nothing to add more.

**Comment by Keremgunduz7** [comment]
I am also closing the issue, if you are going to add more we can reopen it I think.
For now, Great work @Oozankilic .
Thanks.
