### ISSUE TITLE
[Mobile] Login pages being on top of each other after sign-up needs to be fixed

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#277]
***Description*:**

A bug occurs when a user successfully signs-up and the app navigates back to the login screen. This needs to be fixed.

***Reviewer*:** @enginoguzhansenol 

***Task Deadline*:** 31.10.2022 23:00 
***Review Deadline*:** 1.11.2022 11:00

**Comment by kardelendemiral** [comment]
I fixed the bug. See: [the relevant pull request](https://github.com/bounswe/bounswe2022group5/pull/278). I need review @enginoguzhansenol

**Comment by enginoguzhansenol** [comment]
As mentioned in [pull request #278](https://github.com/bounswe/bounswe2022group5/pull/278), the bug is solved. Thank you for your collaboration. Closing the issue now.
