### ISSUE TITLE
Creating and filling: User requirements -> User profile -> Sign up

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#28]
Sign-up page shall be filled.

Deadline: 15/03/2022 11:00

**Comment by bbenginbestas** [comment]
Created and filled sign-up page. Closing the issue now.

**Comment by canberkboun9** [comment]
You might want to open the issue and add @kardelendemiral instead of opening another issue for the Task 1 in [Meeting 2.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-2.2)

**Comment by bbenginbestas** [comment]
Adding @kardelendemiral as assignee and reopening the issue.

**Comment by bbenginbestas** [comment]
There is a sign-up page. Closing the issue for now.
