### ISSUE TITLE
Milestone 1 Presentation Note Taking

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#283]
***Description*:**

@mehmetemreakbulut and @palahb will do the presentation. During the presentation Kerem and I will take notes.

***Todo's*:**
- [x] Create a [page](https://github.com/bounswe/bounswe2022group5/wiki/Milestone-1-Presentation-Notes) for the notes, create a template.
- [x] Take notes during the presentation

***Reviewer*:** @kardelendemiral 

***Task Deadline*:** 01.11.2022 15:00  
***Review Deadline*:** 01.11.2022 16:00

**Comment by kardelendemiral** [comment]
Thanks Canberk! I see that you've created a page for the notes taken in the Milestone 1 presentation and added your notes there. After @Keremgunduz7 also adds the notes he had taken there, we can close this issue.

**Comment by Keremgunduz7** [comment]
I have also added some extra notes. @canberkboun9 has clearly summarized them, there were not very much missed parts.
Also thank you @kardelendemiral for the review. After a final one, we may close the issue.

**Comment by canberkboun9** [comment]
- Thank you @Keremgunduz7, I took a look to what you added.

- I edited the notes a little, it is still not covering a lot of insightful comments, but it was a short presentation anyway.

**Comment by kardelendemiral** [comment]
Thanks for your efforts! I reviewed the page and the notes cover everything that was asked/discussed during our presentation. We can close this issue.
