### ISSUE TITLE
Milestone 1 Evaluation of Tools for Frontend

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#286]
***Description*:**

Evaluation of tools for frontend is going to be written for Milestone 1. The tools are listed below.

***Todo's*:**
- [x] VSCode.
- [x] React.

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 04.11.2022 22:30  
***Review Deadline*:** 04.11.2022 22:50

**Comment by yavuuzsameet** [comment]
Completed the tasks. It can be reviewed @mehmetemreakbulut

**Comment by Keremgunduz7** [comment]
As a member of the Frontend team, evaluation seems realist and adequate to me.
Thanks a lot to your efforts @yavuuzsameet .

**Comment by mehmetemreakbulut** [comment]
Yes. It is very comprehensive. Well done!
Closing issue
