### ISSUE TITLE
Milestone 1 Part 6 and Part 7

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#287]
***Description*:**

Part 6 and Part 7 for [Milestone 1 Group Review](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Milestone_1/M1_Report_Group5.md#group-review) is written by me. It needs a review, the issue is opened late. It includes:

***Todo's*:**

- [x] Overall description of responsibilities that are assigned to each member
- [x] A Summary of work performed by each team member (in tabular)

***Reviewer*:** @Keremgunduz7 

***Task Deadline*:** 04.11.2022 21:00  
***Review Deadline*:** 01.11.2022 22:30

**Comment by Keremgunduz7** [comment]
I have reviewed the parts (6 and 7).
Seems clear and well-structured. 
such a great effort and good job.
Thank you for bringing and organizing them together, on my own behalf and groupmates.

Couldn’t see any points that needs to be changed or refactored. We can close the issue.
