### ISSUE TITLE
[Frontend] Finalizing Login and Signup Pages 

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#289]
***Description*:**

There were some erroneous parts in the login and signup pages such as form field validations. KVKK agreement for signup forms was also missing. These parts in the login and signup pages will be corrected and they will take their final shape.  

***Todo's*:**
- [x] Form field validations will be corrected and aligned with the mobile application.
- [x] KVKK agreement check will be added at the end of signup forms.

***Reviewer*:** @Keremgunduz7 

***Task Deadline*:** 14.11.2022 22:00
***Review Deadline*:** 15.11.2022 12:00

**Comment by Keremgunduz7** [comment]
Hey @burakmert236 . I just wanted to remind you about this issue in case of that you might have forgotten. Also, maybe we can add the warning text and leave the forgot password mechanism to the other milestone and close the issue for now to reopen it in the next weeks.
