### ISSUE TITLE
[Backend] Revising Database Schema with respect to new features

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#292]
***Description*:**

We are adding new features to our application and database design is to be done for these classes: Post, Comment, PostImmage, CommentImage.

***Todo's*:**
- [x] Add new tables to the database schema.
- [x] Document them in the backend meeting notes page.

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 14.11.2022 22:00
***Review Deadline*:** 15.11.2022 12:00

**Comment by canberkboun9** [comment]
- In [Backend Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.3), we documented the new tables added to the schema.

**Comment by irfanbozkurt** [comment]
Done, and been a long time. Everything seems correct.
