### ISSUE TITLE
Preparing a communication plan page

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#3]
Prepare a communication plan page on wiki. This page should include:
- Our different probable communication purposes 
- Which communication means that we will use for these purposes
- When we should and can use these means

Deadline: March 7th, 23:59

**Comment by palahb** [comment]
I created an initial [page](https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page) for our communication plan. After we determine our weekly meeting times, we can add the time for weekly meeting. We can modify the table.

**Comment by oguzhandemirelx** [comment]
I added the Github platform and Audience field to the table.

**Comment by oguzhandemirelx** [comment]
I edited weekly meetings and task review meetings time. All things done.
