### ISSUE TITLE
[Backend] Swagger documentation for team

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#305]
***Description*:**

As backend team we have been developed some APIs. However frontend and mobile teams need to test these APIs. We can create a swagger documentation for endpoints and serve them with an UI.
[Django Rest Swagger](https://django-rest-swagger.readthedocs.io/en/latest/) is one of the useful tools for this purpose.

***Todo's*:**
- [ ] Django Rest Swagger Setup
- [ ] Deploy Swagger UI

***Reviewer*:** @irfanbozkurt  

***Task Deadline*:** 21.11.2022 22:00
***Review Deadline*:** 22.11.2022 12:00

**Comment by mehmetemreakbulut** [comment]
* [Django Rest Swagger](https://django-rest-swagger.readthedocs.io/en/latest/) is deprecated.
* I decided to use [drf-yasg](https://drf-yasg.readthedocs.io/en/stable/index.html). It is widely used and starred by plenty amount of developers on GitHub.

**Comment by canberkboun9** [comment]
Thank you Emre! The documentation also can be found easily on the Sidebar, thanks for that as well. I think this issue need not be open now. Closing it.
