### ISSUE TITLE
Editing Non-Functional, Security Requirements of the project.

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#31]
Additions will be made to the [Requirements page, Security section](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#22-security). I will add several requirements and the final decision will be given in upcoming meetings.

Reviewer: @Keremgunduz7 

Task Deadline: 17.03.2022 - 18:00 GMT+3

**Comment by yavuuzsameet** [comment]
Several requirements are added, more may follow. @Keremgunduz7, feedback would be good at that point.

**Comment by Keremgunduz7** [comment]
Seems nice at first sight.
Maybe we can add an item that covers SQL injections. And also we may move the KVKK statements to the 2.6 Annotations and standards section. We can further discuss these in the meeting.
Thanks for your effort for now, great job!

**Comment by yavuuzsameet** [comment]
A small change is made. I am closing the issue for now.
