### ISSUE TITLE
[Backend] Developing Personal Info API

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#316]
***Description*:**
[Task 1 in Meeting 21.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-21.1#action-items)
Member Info/Personal Info API will be built. It's a class apart from User, including information about the user. Read, Update  operations must be implemented (no all CRUD as Create and Delete is not needed). Its documentation will be added as well.

***Todo's*:**
- [x] Read, Update operations. GET and POST. (for self info of user)
- [x] Read operations. GET. (for showing doctor profile page to a user)
- [x] Unit tests
- [x] Documentation

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 03.12.2022 20:00
***Review Deadline*:** 03.12.2022 23:00

**Comment by canberkboun9** [comment]
Opened the [PR](https://github.com/bounswe/bounswe2022group5/pull/357) for first task.

**Comment by canberkboun9** [comment]
- Other than documentation is done and merged.
- Communication with other teams about how to send requests are done because of the lack of documentation.

**Comment by canberkboun9** [comment]
- Documentations were added to the API Collection.

**Comment by mehmetemreakbulut** [comment]
Looks fine. These endpoints is used for last release. Thank you for all effort!
