### ISSUE TITLE
Improve meeting notes

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2022group5#319]
- Agendas should be described more specifically. Current descriptions are not useful ( i.e.
Talking about tasks done by each team, these tasks were reported to all group members. Each member should put what they will discuss. The agenda should be created collectively.
)

- Items should be enumerated for reference purpose (just like most every swe artifact)

- The discussion should describe what was discussed during the meeting, with emphasis on key aspects

- Action items are missing or not well defined.

**Comment by canberkboun9** [comment]
Thanks for the feedback! 

ps: The last meeting was not a long one, and action items were not specified.

**Comment by canberkboun9** [comment]
[Meeting Notes Template](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-Notes-Template) was revised upon the feedback. Thanks!

**Comment by Keremgunduz7** [comment]
the template looks good to me but I also think that maybe we can further study on preparing an Agenda before the meeting. I think that we are not very good at that particular part.

**Comment by mehmetemreakbulut** [comment]
Issue solved. Closing!
