### ISSUE TITLE
Editing Functional/Forum Requirements

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#32]
#### Description:
Requirements related to the Forum part of the projects will be determined and added to the [related section in the Requirements page](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1121-forum). Final decisions about requirements will be determined in the upcoming weeks.

Reviewer: @oguzhandemirelx 

#### Review Deadline: 17.03.2022 - 20:00 GMT+3

**Comment by palahb** [comment]
- I added user-related requirements to the [Forum requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1121-forum) under User requirements. 
- Since there is some system requirements about the forum also, I created a new section under the System requirements, [Social Platforms Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#122-social-platforms-requirements]). I created three subsections under this title, [Forum](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1221-forum), [Messaging Systems](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1222-messaging-systems), [Chat Bot](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1223-chat-bot), to be in accordance with the User requirements part. 
- I added system-related forum requirements to the newly created [Forum](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1221-forum) section under the System requirements.
- I added some terms to the [Glossary](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#glossary).

The language that I used may not be consistent with the other ones. I tried to obey the user types terminology that we discussed in [Meeting 2.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-2.2#discussion). After we decide on them, we can rewrite these requirements.

Some requirements need to be reviewed since I am not fully sure about them, I added a question mark _(?)_ at the end of them.  We can discuss them in our next meeting.

Also, I think we need to reorganize sections. They seem a bit weird to me.

**Comment by palahb** [comment]
- I edited **1.1.2.1.1**, **1.1.2.1.2** and **1.1.2.1.3** so that doctors can also create posts in the forum.
- I added **1.1.2.1.10** which is about filtering discussion threads by tags.
- I added **1.12.1.12** which is about giving upvote or downvote to a post or a comment. I added necessary definitions to the Glossary.
- I added **1.2.5.1.9** and **1.2.5.1.10** which are about system showing number of upvotes and downvotes of a post or a comment.

I think the titles **1.1.2 Social Interactions** and **1.2.5 Social Platforms Requirements** may be redundant. I think we may set the subtitles below these titles as seperate titles. We can discuss this.

**Comment by palahb** [comment]
* I edited 1.1.2.1.9 so that comments are not tagged.
* I added 1.1.2.1.10 which gives permission of editing tags of any existing post to doctors.

**Comment by palahb** [comment]
@oguzhandemirelx can you review and then close the issue plase?

**Comment by oguzhandemirelx** [comment]
These are adequate requirements for now. We can add extra requirements later on if necessary. Thanks for your effort.
