### ISSUE TITLE
Communication person in Communication Plan

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2022group5#320]
The group communicator and method of communication as well as contact persons for subgroups (if any) should be specified.

https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page

**Comment by mehmetemreakbulut** [comment]
@uskudarli Thanks for feedback! We will consider what is mentioned in the issue and take the necessary actions.

**Comment by canberkboun9** [comment]
- [Communication Plan](https://github.com/bounswe/bounswe2022group5/wiki/Communication-Plan-Page) is revised, thanks for the feedback! 
- We may add communicators for specific sub groups if we decide to choose them.

**Comment by Keremgunduz7** [comment]
I agree with @canberkboun9 , we can also select a member from each team; frontend, backend, mobile in order to reach out in case of an emergent situation.

**Comment by mehmetemreakbulut** [comment]
Issue solved. Closing!
