### ISSUE TITLE
[Frontend] Implementing Discussion Thread Page

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#323]
***Description*:**

Discussion thread page will be implemented. A specific post and its comments must be seen in this page. Also, users will be able to share comments to a post through discussion thread page.

***Todo's*:**
- [x] Initial version of the page which works with mock data will be implemented.
- [x] Necessary backend endpoints will be used for the purposes of upvoting/downvoting a post and sharing a comment.

***Reviewer*:** @yavuuzsameet  

***Task Deadline*:** 28.11.2022 22:00  
***Review Deadline*:** 29.11.2022 12:00

**Comment by burakmert236** [comment]
I implemented the initial version and push [this branch](https://github.com/bounswe/bounswe2022group5/tree/frontend/feature/discussion-thread-%23323).

**Comment by burakmert236** [comment]
I pushed new commits for backend connection. This version works fine but further debugs might be needed depending restructuralization of endpoints of backend.

**Comment by Keremgunduz7** [comment]
Since there will be text in HTML format, maybe you can further check if it is rendered correctly or not.
But overall Looks good to me.
Thanks.

**Comment by burakmert236** [comment]
Thanks for your review, I enabled rendering post and comment strings as HTML and pushed to the [same branch](https://github.com/bounswe/bounswe2022group5/issues/323). We should also enable this feature in homepage as well.
