### ISSUE TITLE
[Backend] Extending Upvote-Downvote API for comments

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#324]
***Description*:**
After [PR] implemented by @oguzhandemirelx have been merged , now, we can upvote and downvote the posts. However it can not be used to voting comments. So I will improve the API so that comments will be voted.

***Todo's*:**
- [x] Upvote Comment endpoint
- [x] Downnote Comment endpoint

***Reviewer*:** @canberkboun9  

***Task Deadline*:** 27.11.2022 20:00
***Review Deadline*:** 27.11.2022 23:00

**Comment by mehmetemreakbulut** [comment]
* I have opened PR. See:
  * #328 

* I have also changed name of post voting services.
* Need Review @canberkboun9

**Comment by oguzhandemirelx** [comment]
I tested your code, and everything is in order. So that we may close this issue, we merged the branch. I appreciate your work.
