### ISSUE TITLE
Editing Functional/User Requirements section of the project

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#33]
Requirements will be added to [Functional Requirements/User Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1-functional-requirements). 

**Reviewers:** @canberkboun9 , @enginoguzhansenol 

**Task Deadline:** 17.03.2022 - 18:00 GMT+3
**Review Deadline:** 17.03.2022 - 20:00 GMT+3

**Comment by kardelendemiral** [comment]
- I created the sections 1.1.1.4.1, 1.1.1.4.2 and 1.1.1.5. 
- I added new requirements to the sections 1.1.1.1, 1.1.1.2, 1.1.1.3, 1.1.1.4 and 1.1.1.5.
See: [Functional Requirements/User Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#11-user-requirements).

Additional requirements can be suggested by the team members.

**Comment by kardelendemiral** [comment]
Since it is not decided yet whether our application will have a 'follow' function for the users, I did not add the following requirements. If we decide that this functionality will be provided, they can be added. 

1.1.1.3 Profile Pages:
  * Users shall be able to follow other users going to their profile pages.
  * Users shall be able to see their follower list in their profile pages. 
  * Users shall be able to the followed users list in their profile pages.

**Comment by canberkboun9** [comment]
- Users shall be able to follow other users (by) going to their profile pages. -> Maybe this addition might clear the ambiguity.
Requirements:
- Under 1.1.1.1: Users shall verify their identity (by providing authentication via their doctor's ID, diploma, or some other legal verification method.)
- We might want to talk about " nickname" feature.
- Users shall (be able to) register their previous medical conditions to the system.
- Under 1.1.1.2: Users shall be able to sign-in if they forget their password if they can verify their identity and they shall choose a new password. -> We might want to change this such that it's main idea would be "forgot password" mechanism.
- Under 1.1.1.3: Users shall be able to sign-out. -> I am not sure whether this requirement should be in this section.
- Enumeration of the requirements to match with other sections would be nice.
- Nice work! Eline sağlık.

**Comment by bbenginbestas** [comment]
Great work Kardelen! I think 'follow' functionality sounds great and we can discuss it further. 
Also great review Canberk, I went ahead and changed some parts according to your review.
* Under 1.1.1.1: Users shall (be able to) register.
* Under 1.1.1.2: Changed the text to forget password mechanism.
* Enumerated so it would match other sections.
Also:
* Changed the position of some entries so that it would look better and would be more organized.
* Changed some of the words.

**Comment by kardelendemiral** [comment]
I made modifications according to the Meeting 2.1 feedback:
- Added definitions of User, Registered User, Doctor, Member, Guest User, Personal Information, Public Personal Information, Protected Personal Information and Private Personal Information to the [Glossary](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#glossary).
- Modified the requirements according the user types specified in the glossary.
- Modified the requirements according the personal information types specified in the glossary.
- Removed the User Types section and added the requirements under this section to other appropriate sections.
- Changed 6 characters for the password requirement to 8 characters.
- Divided the profile picture requirements into two which are for doctors: profile picture, for members: avatar.
- Changed all "previous medical conditions" terms to "medical history".

**Comment by canberkboun9** [comment]
Great work! Consistency is achieved for user requirements. I think we may call this part done and close the issue. However, if needed in the future, it could be opened again and further modifications could be added as comments.

**Comment by kardelendemiral** [comment]
Thank you for the review @canberkboun9. I am closing the issue for now.
