### ISSUE TITLE
[Backend] Getting all posts of a user

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#332]
***Description*:**

We have two endpoints to fetch posts: get by id and get all with pagination.
However, users might need to fetch posts created by a specific user.

***Todo's*:**
- [x] Implement get_posts_of method and expose the API
- [x] Handle pagination

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 28.11.2020 00.00

**Comment by irfanbozkurt** [comment]
See the [wiki](https://github.com/bounswe/bounswe2022group5/wiki/API-Documentation#:~:text=Get%20Posts%20of%20a%20User%20with%20Pagination) for explanation of the endpoint.

**Comment by mehmetemreakbulut** [comment]
Updating API Documentation is very crucial. Congratulations!
I have reviewed the changes on PR.
