### ISSUE TITLE
[Backend] Getting upvoted posts of a user

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#334]
***Description*:**

Users can upvote posts, and anyone might want to retrieve which posts they upvoted.

***Todo's*:**
- [x] Implement get_upvoted_posts method and expose the API
- [x] Handle pagination

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 28.11.2020 00.00

**Comment by mehmetemreakbulut** [comment]
Reviewed the PR. See comments.
Merged!
