### ISSUE TITLE
[Backend] Getting upvotes (articles) of a user

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#336]
***Description*:**

Users can upvote articles, and anyone might want to retrieve which posts they upvoted.

***Todo's*:**
- [x] Implement get_upvoted_articles method and expose the API
- [x] Handle pagination

***Reviewer*:** @mehmetemreakbulut  

***Task Deadline*:** 28.11.2020 00.00

**Comment by mehmetemreakbulut** [comment]
See PR review. LGTM!
Closing.
