### ISSUE TITLE
Editing Functional/Search Requirements section of the project.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#34]
Requirements are going to be added to the [search](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#122-search-requirements) section. 

Reviewer: @kardelendemiral 

Task Deadline: 17.03.2022 - 18:00 GMT+3
Review Deadline 17.03.2022 - 20:00 GMT+3

**Comment by Keremgunduz7** [comment]
I have tried to list the requirements in terms of search for the project. A little bit of review would be great at this stage. @kardelendemiral maybe you can take a look at it. You can find them under the [Search Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#122-search-requirements) heading. Thanks in advance already now.

**Comment by kardelendemiral** [comment]
They seemed more than sufficient to me at this stage. Thanks for your effort. However, please do not close the issue yet. We may review the sub-categorization of requirements and decide to make modifications in the next meeting as a group.

**Comment by Keremgunduz7** [comment]
Thank you for your comments. I agree, the issue are going to stay open at least up until the meeting.

**Comment by Keremgunduz7** [comment]
We are going to ask for the filtering and sorting requirements under the search requirements to the TA. Except those, I think we can close this issue at least for now. If a need of rearrangement emerges, we may open up the issue again.

**Comment by palahb** [comment]
I moved search requirements from System Requirements section to User Requirements section as suggested by the customer in [Customer Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-3). I changed the expressions to be consistent with User Requirements. Can you review it @Keremgunduz7 ?

**Comment by Keremgunduz7** [comment]
It seems fine, we can close the issue again. Thanks for your edition and review.
