### ISSUE TITLE
[Milestone Presentation] Preparing scenarios for the Milestone 2

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#361]
***Description*:**
[Task 2 in Meeting 21.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-21.1#action-items)
We had created new scenarios for Milestone 1 before. We should do new ones that are covering new functionalities we added to our app. This is a part of preparation for the presentation on Tuesday.

***Todo's*:**

- [x] Documentation on wiki (new page)
- [x] Scenario creation
- [x] Image insertion

***Reviewer*:** @palahb 

***Task Deadline*:** 04.12.2022 21:00
***Review Deadline*:** 05.12.2022 12:00

**Comment by canberkboun9** [comment]
- Scenarios are written with the help of @mehmetemreakbulut. 
- We attended a meeting to present our ideas for the scenarios to @enginoguzhansenol and @yavuuzsameet

**Comment by canberkboun9** [comment]
- @bbenginbestas added images for mobile.
- Web images are needed.
- Acceptence Criteria will be added soon.

**Comment by mehmetemreakbulut** [comment]
Deliverables is done! Congrats! Closing issue.
