### ISSUE TITLE
[Frontend] Adding Geolocation Feature for Discussion Thread Page

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#364]
***Description*:**

Shared geolocation of a post must be visible to other users. A google maps link will be provided for post geolocation. Users will be able to share a comment with their geolocation.

***Todo's*:**
- [x] A google map link for post geolocation should be added to the discussion page.
- [x] Adding geolocation info while sharing a comment will be implemented.

***Reviewer*:** @yavuuzsameet 

***Task Deadline*:** 05.12.2022 20.00
***Review Deadline*:** 05.12.2022 23.59

**Comment by burakmert236** [comment]
I completed tasks and push to [this branch](https://github.com/bounswe/bounswe2022group5/tree/frontend/feature/discussion-thread-geolocation-%23364).

**Comment by yavuuzsameet** [comment]
The code has been merged, closing the issue.
