### ISSUE TITLE
[Frontend] Pagination for Posts and Articles at Home page

### ISSUE THREAD

**Issue by Oozankilic** [bounswe/bounswe2022group5#367]
***Description*:**

Articles and posts at Homepage should be shown with pagination.

***Todo's*:**
- [x] Fetching elements from backend according to page number and item per page informations.
- [x] Showing elements according to the data

***Reviewer*:** @Keremgunduz7  

***Task Deadline*:** 03.12.2022 14.00
***Review Deadline*:** 04.12.2022 23:00

**Comment by Keremgunduz7** [comment]
Work looks great to me. Thanks a lot to your efforts, I have also added a small comment on the PR. We can automatically close this issue after merging PR.

**Comment by Oozankilic** [comment]
PR is merged to the master without any problem. Issue will be closed.
