### ISSUE TITLE
Editing Functional/Notifications Requirements section of the project

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#37]
Notifications Requirements will be searched and added to the [Notifications](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#113-notifications) section.

Reviewer: @burakmert236

Task Deadline: 17.03.2022 - 18:00 GMT+3
Review Deadline 17.03.2022 - 20:00 GMT+3

**Comment by enginoguzhansenol** [comment]
Added Notification requirements to the [Notifications](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#113-notifications) section of Requirements.
* There is a question mark about 'follow' functionality that we can discuss in our next meeting.
* Also, I could not find any subheading under Notifications section. Maybe we can find a way to expand this section.

**Comment by burakmert236** [comment]
Seems pretty nice to me. Since we decided not to implement following feature, you can delete related requirement.

**Comment by enginoguzhansenol** [comment]
Some changes are done in the Notifications Requirements done:
* Notification about the following feature has been removed.
* Notification about the chatting feature has been removed.
* Listing arranged according to other subheadings by adding subheading "1.1.3.1 Notifications"

**An Idea:** We can create two subheadings called "User Notifications" and "Doctor Notifications"

**Comment by burakmert236** [comment]
I think this version of the requirements is great, dividing notifications into two subgroup is not necessary. In the future, if we have confusing amount of notifications requirements, we may divide it.

**Comment by enginoguzhansenol** [comment]
Thanks for the review. Closing the issue.
