### ISSUE TITLE
Customizing the “issues” by Specializing Them. i.e. Creating Varying Labels.

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#4]
### Description: 
We have several generic labels built-in on Github Wiki. This week, we will be conducting research for repositories. While doing that, we may find creative labels that we could add to our wiki page. 

### To Do:
- Everybody could do an addition to the labels. Team member who makes an addition should add oneself as an assignee. (If 10+, no problem)
- We can do our additions by commenting under this issue. While doing that, the sites should be referenced.
- In the end we could open a page for presenting our new labels. (We are not sure if this is necessary, and this will be asked)

**Comment by canberkboun9** [comment]
I have added "research" label. Simply can be added on issues concerning research required.

**Comment by mehmetemreakbulut** [comment]
I have added "Low","Medium" and "High" priority labels. They can be added on issues according to their importance level.

**Comment by mehmetemreakbulut** [comment]
I have added some "Category" labels.

**Comment by mehmetemreakbulut** [comment]
https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
This link summarized the good labels for a repo. It is a helpful guide to understand usage of labels.

**Comment by mehmetemreakbulut** [comment]
I think we can add a "Everyone" label or "Group Work". Indicates that it is an issue that everyone should look at and deal with. Tasks which is like "creating personal wiki pages" are good examples for this label.

**Comment by canberkboun9** [comment]
### To Do:
- Labels in the wiki: Type: Code, Type: Design, Priority: Urgent, Color coding the flow.
- Editing some of the descriptions.
According to the [Meeting 1.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-1.2)

**Comment by canberkboun9** [comment]
Enhancement encompasses Code and Design,
Created the Urgent Priority label

**Comment by canberkboun9** [comment]
We currently need no more labels. Closing the issue for now.
