### ISSUE TITLE
Editing Non-Functional, Privacy Requirements of the project. 

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#40]
Additions will be made to the [Requirements page, Privacy section](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#23-privacy). I will add several requirements and the final decision will be given in upcoming meetings.

Reviewer: @makifyilmaz 

Task Deadline: 17.03.2022 - 18:00 GMT+3

**Comment by mehmetemreakbulut** [comment]
Some initial privacy requirements are added. Some proviacy policies of health platforms are reviewed.
Sources: 
* https://rebelsguidetopm.com/gdpr-project-management/
* https://ico.org.uk/for-organisations/guide-to-data-protection/introduction-to-dpa-2018/some-basic-concepts/#4
* https://www.aksigorta.com.tr/yasal/kisisel-verilerin-korunmasi
* https://www.termsfeed.com/blog/privacy-guidelines-health-apps/

These links can be stored in another page in wiki.

**Comment by makifyilmaz** [comment]
Looks very good. We can discuss them also in the meeting, We can also add more requirements when needed.

**Comment by makifyilmaz** [comment]
I think these requirements are enough at this stage. We can close the issue.
