### ISSUE TITLE
Logo and Name Information

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#401]
***Description*:**

As we have decided in #185, the name of the app is Hippocrates. And along with that name, we had an idea about the logo. In light of our idea, I have come up with a logo design that we are currently using in the navigation bar of the frontend. With this issue, I am aiming to inform other teams and share the logo and the text photo as a comment on this issue so that they remain visible to those want to see. To that extend, I am adding a reviewer for each team.

***Todo's*:**
- [x] Share logo as a comment.

***Reviewer*:** @mehmetemreakbulut @kardelendemiral   

***Task Deadline*:** 05.12.2022 14:00
***Review Deadline*:** 05.12.2022 23:00

**Comment by yavuuzsameet** [comment]
This is the logo.
![istockphoto-1412776750-612x612-removebg-preview](https://user-images.githubusercontent.com/73655554/205593230-f2846d6c-36db-4694-9e7a-fdde4555f14c.jpg)

**Comment by yavuuzsameet** [comment]
This is the text version that we are using in the navigation bar.
![cooltext424595263627775](https://user-images.githubusercontent.com/73655554/205593357-77705b01-a6bb-4e89-aecb-fde86cf37440.png)

**Comment by canberkboun9** [comment]
In the group, majority liked the design. Thank you Samet!

**Comment by kardelendemiral** [comment]
Thank you for the designs @yavuuzsameet . Loved it !

**Comment by mehmetemreakbulut** [comment]
We are done with logo and name. Closing issue!
