### ISSUE TITLE
Editing Non-Functional, Performance Requirements of the project.

### ISSUE THREAD

**Issue by busetolunay** [bounswe/bounswe2022group5#41]
Description: Requirements will be added to [Non-Functional Requirements](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#2-non-functional-requirements) page
Reviewer: @mehmetemreakbulut 
Task Deadline: 17.03.2022 - 18:00 GMT+3
Review Deadline: 17.03.2022 - 20:00 GMT+3

**Comment by busetolunay** [comment]
I added the performance requirements after doing a research. Performance requirements and spesific numbers needs to be decided as a team. After the meeting I will make changes accordingly. I need a review.

**Comment by mehmetemreakbulut** [comment]
These performance requirements seems sufficient and clear. Some extra requirements can be added in the forthcoming weeks.

**Comment by palahb** [comment]
It seems that we can close the issue. Thank you Buse!
