### ISSUE TITLE
Editing Functional/Articles Requirements 

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#42]
#### Description:
Requirements related to the Articles part of the project will be determined, a new section in requirements page for our project's Wiki part will be created  and requrements will be added to the this section. Final decisions about requirements will be determined in the upcoming weeks.

Reviewer: @oguzhandemirelx

#### Review Deadline: 21.03.2022 - 20:00 GMT+3

**Comment by palahb** [comment]
I created the section [1.1.2.4 Wiki](https://github.com/bounswe/bounswe2022group5/wiki/Requirements#1124-wiki) and added some requirements. Also added some definitions to the Glossary. I am not sure about whether I placed the section in the right place or not, we should discuss it I think.

**Comment by palahb** [comment]
Change of terminology: We use "Articles" instead of "Wiki"

**Comment by palahb** [comment]
@oguzhandemirelx can you review and then close the issue plase?

**Comment by oguzhandemirelx** [comment]
Looks nice, I didn't see any problem. I think we can close this issue. Many thanks for all your work.
