### ISSUE TITLE
Milestone 2 Presentation Notes 

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#428]
***Description*:**

A new wiki page should be created for Milestone 2 Presentation notes and notes taken by the members should be added there. 

***Todo's*:**
- [x] A wiki page will be created.
- [x] The notes taken during Milestone 2 Presentation will be added there.

***Reviewer*:** @canberkboun9 

***Task Deadline*:** 12.12.2022 23:59 
***Review Deadline*:** 13.12.2022 15:00

**Comment by kardelendemiral** [comment]
The page is created and the notes are added there. See: [Milestone 2 presentation Notes](https://github.com/bounswe/bounswe2022group5/wiki/Milestone-2-Presentation-Notes). It needs review @canberkboun9

**Comment by canberkboun9** [comment]
Thank you Kardelen! 
- I edited two typos.
- Other than that it is well written.
- Closing the issue.
