### ISSUE TITLE
Creating Scenario #2 and Mockups

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#43]
#### To Do:
- Creating Scenario 2 wiki page and creating Scenario 2. (Anchor text will be added)
- Designing the mockups for Scenario 2.

Reviewer: @bbenginbestas @busetolunay @enginoguzhansenol @makifyilmaz  

#### Review Deadline: 21.03.2022 - 20:00 GMT+3

**Comment by Keremgunduz7** [comment]
I have also replaced some acceptance criteria besides to the ones that we have decided in the meeting.
Added:
- 1.2.1.1.9
Removed:
- 1.1.2.1.11

**Comment by yavuuzsameet** [comment]
Website mockup is added with @Keremgunduz7 and actions are edited.

**Comment by makifyilmaz** [comment]
I think the scenario is very creative and with the mockups it looks very good. Thank you for your efforts. My suggestions are :

1.  In the acceptance criteria, 1.1.1.2.1(for members) should be changed with 1.1.1.2.2(for doctors).
2.  To the last mockup we should add the expression "She closes the app".
3.  We may change the "submit button" expression in the 5. action item as "comment button" to be consistent with the mockup.
4. We need to add mobile mockups until today 11.59 pm.

**Comment by mehmetemreakbulut** [comment]
Mobile mockups are added with @palahb .

**Comment by palahb** [comment]
> I think the scenario is very creative and with the mockups it looks very good. Thank you for your efforts. My suggestions are :
> 
> 1. In the acceptance criteria, 1.1.1.2.1(for members) should be changed with 1.1.1.2.2(for doctors).
> 2. To the last mockup we should add the expression "She closes the app".
> 3. We may change the "submit button" expression in the 5. action item as "comment button" to be consistent with the mockup.
> 4. We need to add mobile mockups until today 11.59 pm.

I did necessary arrangements. Can you review one more time?

**Comment by palahb** [comment]
@makifyilmaz :
> I think the scenario is very creative and with the mockups it looks very good. Thank you for your efforts. My suggestions are :
> 
> 1. In the acceptance criteria, 1.1.1.2.1(for members) should be changed with 1.1.1.2.2(for doctors).
> 2. To the last mockup we should add the expression "She closes the app".
> 3. We may change the "submit button" expression in the 5. action item as "comment button" to be consistent with the mockup.
> 4. We need to add mobile mockups until today 11.59 pm.

I did necessary arrangements according to your review and updated some of mobile mockups. Can you review one more time?

**Comment by busetolunay** [comment]
Scenario and actions looks very creative and well designed. App and web mockups are consistent . Only thing that caught my eye  is that the symbols at the navigation bar are the same colour and it is little bit hard to understand which category (article, post etc) you are in. Except that I also think the work is done.
