### ISSUE TITLE
Chatbot conversations creation.

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#433]
***Description*:**

Task 5 in [Meeting 23.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-23.1)

Our Chatbot Section will be implemented. It will have a _decision tree_ to hold the conversation: questions and answers. This will not be a complex chatbot, e.g. having NLP features. I plan to document the conversations in JSON format. 

It will consist of two parts:
- A simple manual explaining how to use the app.
- A recommender and helper in diagnosis and traversing the Posts, Articles via using correct Categories.

***Todo's*:**
- [x] Chatbot Conversations, Questions & Answers
- [x] JSON Documentation

***Reviewer*:** @Oozankilic, @Keremgunduz7

***Task Deadline*:** 19.12.2022 20:00
***Review Deadline*:** 20.12.2022 22:00

**Comment by canberkboun9** [comment]
- Initial version is done and documented here: [Chatbot Conversation Tree](https://github.com/bounswe/bounswe2022group5/wiki/Chatbot-Conversation-Tree)

**Comment by canberkboun9** [comment]
- Initial version is agreed upon in the [Meeting 24.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-24.1). Thus, I am continuing to fill the tree.

**Comment by canberkboun9** [comment]
- I uploaded version 1.1, a new version: Filled the tree, added some new answer types. 
- Review is needed.

**Comment by Oozankilic** [comment]
There are at least five edge at the conversation tree. I think it is pretty enough for a beginning version. If project is wanted to be developed more, tree can be deeper. For now it seems great. Thank you for your collaboration Canberk. After @Keremgunduz7 's review the issue could be closed.

**Comment by Keremgunduz7** [comment]
I think it is enough for us to implement the basic version of the ChatBot for now.
In the future, if needed we maybe can increase the depth of the tree but I don't think it is much necessary right now.
Thanks a lot for your efforts. Great Work!.

**Comment by canberkboun9** [comment]
Thanks for the review. Closed the issue.
