### ISSUE TITLE
Creating Scenario #1 and Mockups 

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#44]
#### Description: 
Assignment 2 for the project is Scenarios&Mockups. We will create a scenario where a patient creates a post in the app for his discomfort, and designing mockups for this scenario.

#### To Do:
- Creating [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1) wiki page and creating Scenario 1. 
- Designing the mockups for Scenario 1.

Reviewer: @palahb , @mehmetemreakbulut , @yavuuzsameet , @Keremgunduz7 

#### Review Deadline: 21.03.2022 - 20:00 GMT+3

**Comment by canberkboun9** [comment]
Scenario 1 wiki page is created, added to the Sidebar.
Created [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1) with meeting assignees. Also discussed contents of the app with other groups to have a consistent progress for the Scenarios and Mockups.
Designed mockups for Scenario 1 for website, not mobile.

**Comment by Keremgunduz7** [comment]
This scenario represents a great example at the moment. It seems that the only missing is the mobile mockup. We can add it as soon as possible.

**Comment by palahb** [comment]
With mobile mockups added, this scenario seems perfect in my opinion. Thank you all for your effort. I think we can close the issue after some other reviewers see the page.

**Comment by canberkboun9** [comment]
Thank you Halil, one review might be enough as we discussed it a lot earlier. However, it can remain open for just one more reviewer's comment on the mockups.

**Comment by canberkboun9** [comment]
Thanks for the reviews. Closing the issue
