### ISSUE TITLE
[Backend] Refactor search code

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#445]
***Description*:**

The code for searching is not dynamic at all. Adding new functionality is hard.
It's basically based on "category" and "keyword" information, but logic blocks make it very hard to read and add new things.

***Todo's*:**
- [x] Simplify the search code

***Reviewer*:** @oguzhandemirelx    

***Task Deadline*:** 17.12.2022 22:00

**Comment by oguzhandemirelx** [comment]
Good point. We can also use this code block to get related posts for a user. Thanks for your effort.
