### ISSUE TITLE
[Backend] Geospatial search implementation

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/bounswe2022group5#447]
***Description*:**

Based on my research last week (see finalized results [here](https://github.com/bounswe/bounswe2022group5/issues/440)), today I decided to implement [Spherical Law of Cosines in a query](https://en.wikipedia.org/wiki/Spherical_law_of_cosines) for distance-based search queries.

Here's the query:
![Screen Shot 2022-12-17 at 16 57 57](https://user-images.githubusercontent.com/38441731/208245519-4a3893e0-3a24-4ab6-89eb-1777ca8398c7.png)

***Todo's*:**
- [x] Find a way to add this custom query into Django's filtering

***Task Deadline*:** 17.12.2022 22:00

**Comment by oguzhandemirelx** [comment]
Thanks for your effort buddy. Nice work! I'm closing the issue.
