### ISSUE TITLE
Creating Scenario #3 and Mockups

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#45]
**Description:** Assignment 2 for the project is Scenarios&Mockups. A scenario where a patient opens a wiki/encyclopedia article and rates the page will be created and mockups will be set up. 

**Reviewer:** @canberkboun9, @burakmert236, @kardelendemiral, @oguzhandemirelx

**Task Deadline:** 21.03.2022 - 18:00 GMT+3
**Review Deadline:** 21.03.2022 - 20:00 GMT+3

**Comment by enginoguzhansenol** [comment]
[Scenario 3 page](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-%233) has been opened in Wiki and added to the sidebar.
A scenario and mockups template is created similarly to other scenarios and mockups.
A realistic user and use case scenario are created.

**Comment by makifyilmaz** [comment]
Web page Mockups for the scenario are added to the [Scenario 3 page](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-%233#mockups).

**Comment by canberkboun9** [comment]
#### Review:

**Comment by canberkboun9** [comment]
#### Review:
- I am not sure whether we should keep 1.2.1.2.1, and 1.2.1.2.2 as requirements, after discussing it we may need deleting them.
- Edited a typo in action 2 under Mockups
- Great story idea and action items, creative and useful topic.
- We may want to show the rate Brad gave to topic on the last mockup, via coloring or boldness etc.
- I think we should append a sentence such as "He closed the app" on the last action
- Great work! We should not forget adding mobile mockups.

**Comment by bbenginbestas** [comment]
Edited comments, now links redirect to the updated URL correctly.

**Comment by busetolunay** [comment]
Edited the search bar at the article reading page according to the reviwes at the meeting.

**Comment by kardelendemiral** [comment]
I think it looks ok now. Thanks for the effort.
