### ISSUE TITLE
[Mobile] Comment deletion functionality

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#456]
***Description*:**

Comment deletion functionality should be implemented for the mobile application. 

***Todo's*:**
- [x] Comment deletion functionality will be added.

***Reviewer*:** @palahb 

***Task Deadline*:** 21.12.2022 12:00
***Review Deadline*:** 21.12.2022 23:59

**Comment by kardelendemiral** [comment]
The functionality is implemented. See [the related PR](https://github.com/bounswe/bounswe2022group5/pull/519). It needs review.

**Comment by palahb** [comment]
Comment deletion is implemented and works perfectly. Thank you Kardelen.
