### ISSUE TITLE
Adding Annotations and Standards to Requriements

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#46]
#### Description: 
Listing Annotations and Standards is needed for requirements.

#### To Do:
- Some general research will be done for this purpose

Reviewer: @makifyilmaz 

#### Review Deadline: 21.03.2022 - 20:00 GMT+3

**Comment by makifyilmaz** [comment]
I think they are enough for this stage. We can add further requirements when we need. Thank you for your work.

**Comment by palahb** [comment]
I think we can close the issue. Thank you Emre!
