### ISSUE TITLE
[Backend] Annotation Schema Bugfix

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#469]
Description:
Frontend team found two bug on annotation endpoints. This issue for fixing them.

***To Do*:**
- [x] `name` field of author will be added to Annotation Schema
- [x] Update Image annotation functionality added

***Reviewer*:** @oguzhandemirelx       

***Task Deadline*:** 24.12.2022 12:00
***Review Deadline*:** 24.12.2022 18:00

**Comment by oguzhandemirelx** [comment]
All things are done, bugs fixed. Thanks for your contribution.
