### ISSUE TITLE
[Backend] Add username/name search to search functionality

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#475]
***Description*:**
Users but especially Doctors can be searched via search bar by typing the name or username. Posts of that user will be given

***Todo's*:**
- [x] Add user search to post search
- [x] Add user search to article search

***Reviewer*:** @canberkboun9     

***Task Deadline*:** 24.12.2022 22:00

**Comment by canberkboun9** [comment]
Nice work! 
- Merged the [Pull Request #476](https://github.com/bounswe/bounswe2022group5/pull/476). A problem occured, or it said it occured but it wasn't. We checked it and there is no problem. 
- Merged a complementary PR for check: [Pull Request #477](https://github.com/bounswe/bounswe2022group5/pull/477)
