### ISSUE TITLE
Editing the Acceptance Criteria of Scenarios and Mockups

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#48]
During [Customer Meeting 2](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-2) and [Meeting 5.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-5.1), it is decided that some requirements should be changed or deleted. After changes and deletions, the numbering of acceptance criteria is corrupted. The numbering should be fixed.

Reviewer: @canberkboun9, @kardelendemiral 

Task Deadline: 03.04.2022 - 18:00 GMT+3
Review Deadline: 03.04.2022 - 20:00 GMT+3

**Comment by yavuuzsameet** [comment]
I made the necessary changes to the acceptance criteria of the scenarios.

- [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1#acceptence-criteria):
1.1.2.1.9 🠒 changed ~~posts and comments~~ to comments.
1.2.1.1.2 🠒 changed all of the statement.

- [Scenario 2](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-2#acceptance-criteria):
1.1.1.1.4 🠒 numbering edited, previously it was ~~1.1.1.1.5~~.
1.1.2.1.5 🠒 changed ~~all users~~ to users.
1.1.2.1.9 🠒 changed ~~posts and comments~~ to comments.
1.2.1.1.9 🠒 changed all of the statement.

- [Scenario 3](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-3#acceptance-criteria):
1.1.1.1.4 🠒 numbering edited, previously it was ~~1.1.1.1.5~~.

**Comment by yavuuzsameet** [comment]
Changes made, need review.

**Comment by canberkboun9** [comment]
> I made the necessary changes to the acceptance criteria of the scenarios.
> 
> * [Scenario 1](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1#acceptence-criteria):
>   1.1.2.1.9 🠒 changed ~posts and comments~ to comments.
>   1.2.1.1.2 🠒 changed all of the statement.

"to comments" should be "to posts", I think. This may be a typo. In scenario 2, as well.

Other than that, it seems correct to me.

Thank you.

**Comment by yavuuzsameet** [comment]
> "to comments" should be "to posts", I think. This may be a typo. In scenario 2, as well.

Yes, you are 100% right. I wrote ''to posts'' in Scenarios, but ''to comments'' above. I am editing the explanation now. Thank you.

**Comment by kardelendemiral** [comment]
They seem ok right now. Nice work!

**Comment by yavuuzsameet** [comment]
Then the issue is being closed now.
