### ISSUE TITLE
[Frontend][Mobile] Implementing the tree Q/A configurations of the ChatBot.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#489]
***Description*:**

We are using [Kommunicate.io](https://docs.kommunicate.io/docs/web-installation.html) for the chatbot and integrated it to the both mobile and frontend. However, [These](https://github.com/bounswe/bounswe2022group5/wiki/Chatbot-Conversation-Tree) conversations need to be added to the bot's configurations by hand.

***To Do*:**
- [ ] Add configurations for the parent nodes and create button hierarchy.
- [ ] Add redirections separately for both mobile and frontend on the leaf nodes to the categories

***Reviewer*:** @kardelendemiral @yavuuzsameet        

***Task Deadline*:** 26.12.2022 22:00
***Review Deadline*:** 26.12.2022 23:00

**Comment by enginoguzhansenol** [comment]
We will use the chatbot integration that mentioned above for mobile. The Chatbot conversations look nicely added. Great work! Redirections should be added to the leaf nodes for mobile also. See issue #465

**Comment by Keremgunduz7** [comment]
Added common conversations with mobile and frontend as @enginoguzhansenol stated. Now, @Oozankilic are going to add redirections for the frontend where we have separated the bots as mobile and frontend at this point.

**Comment by Oozankilic** [comment]
Redirections are added. Now chatbot for frontend is working as it should. Thank you for your collaborations guys!

**Comment by enginoguzhansenol** [comment]
The chatbot was also done in the mobile applications. Redirections cannot be made since it was not possible to redirect a screen in a mobile application. We can close this now. Great effort!
