### ISSUE TITLE
Creating Customer Meeting 2 Page

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#49]
#### Description:
A page for our 2nd customer meeting, which was on March 30th, will be created and details about the meeting will be uploaded.

Reviewer: @oguzhandemirelx @burakmert236 

#### Review Deadline: 03.04.2022 - 20:00 GMT+3

**Comment by palahb** [comment]
I created a page for [Customer Meeting 2](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-2) and uploaded meeting info that I have. @canberkboun9  and @Keremgunduz7 , can you edit it according to your meting notes?

**Comment by canberkboun9** [comment]
I made my additions under Agenda and Discussion to the page @palahb opened.

**Comment by burakmert236** [comment]
I think customer meeting notes are great, we can re-write chatbot requirements thanks to these notes. We can also think about comment sorting mechanism in the next meeting.

**Comment by Keremgunduz7** [comment]
I have also added some feedbacks given by the customer according to my notes that I have taken in the meeting.
And, @burakmert236 thank you for your review.

**Comment by oguzhandemirelx** [comment]
Meeting notes are so clear. Indentations and other designs are great. We can close the issue. Thanks for your hard work.
