### ISSUE TITLE
Creating Scenarios for the Final Milestone Presentation

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#518]
***Description*:**
[Task 13 in Meeting 24.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-24.1#action-items)
We had created new scenarios for Milestone 1&2 before. We should do new ones that are covering new functionalities we added to our app, but most importantly, the most complex and fancy ones. This is a part of preparation for the presentation on Tuesday.

***Todo's*:**

- [x] Documentation on wiki (new page)
- [x] Scenario creation
- [x] Image insertion

***Reviewer*:** @mehmetemreakbulut, @burakmert236, @enginoguzhansenol 

***Task Deadline*:** 27.12.2022 02:00
***Review Deadline*:** 27.12.2022 12:00

**Comment by canberkboun9** [comment]
- Created and wrote the scenarios before the Final Presentation.
- I presented the demo, that's why the scenarios documentation was not a priority.
- I will document them now in the wiki.

**Comment by canberkboun9** [comment]
- [Scenario 1 for CMPE451:Final Milestone](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-1-for-Final-Milestone) is done except acceptance criteria and screenshots from Mobile part.
- Added to the Sidebar.

**Comment by canberkboun9** [comment]
- [Scenario 2 for CMPE451:Final Milestone](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-2-for-Final-Milestone) is done except acceptance criteria and screenshots from Mobile part.
- Added to the Sidebar.

**Comment by mehmetemreakbulut** [comment]
Looks okey! Closing issue!
