### ISSUE TITLE
Creating a Sequence Diagram for Searching an Article by Tags

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#52]
Description: Creating a Sequence Diagram of a use case for searching an article in the application. This search is performed by tags.

Reviewer: @mehmetemreakbulut 
Review Deadline: 10.04.2022 15.00
Task Deadline: 10.04.2022 12.00

**Comment by yavuuzsameet** [comment]
I think we can add the 'return' keyword to dashed lines. return searchEngine, return searchHistory, etc.

**Comment by yavuuzsameet** [comment]
After the meeting held yesterday, and a little additional research I found out that no need for 'return' keyword. Hereby, I withdraw my request to add the 'return' keyword to the diagram. It is now good as it is. Thanks.

**Comment by mehmetemreakbulut** [comment]
I think the diagram is done successfully. For more suggestions, we can make the final review after the customer's return.

**Comment by burakmert236** [comment]
We updated the diagram according to customer's review and now I'am closing the issue.
