### ISSUE TITLE
Creating a Sequence Diagram for Approving Article 

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#53]
#### Description: 
Creating a Sequence Diagram of a use case for approving an article in the application. This search can be performed according to many criteria such as the article's tags, category, author and date.

Reviewer: @palahb

**Comment by canberkboun9** [comment]
I moved some arrows to depict the chronological sequnce of events.

**Comment by mehmetemreakbulut** [comment]
I think the final version of the diagram considering the suggestions in the meeting is appropriate. We can take action after review.

**Comment by palahb** [comment]
The sequence diagram seems good, but I have some suggestions: 
- I think places of the alternatives need to be revised.  I think it is redundant and somehow seems a bit odd to have 2 alternatives that says the same thing. The inner alternative is enough and also the correct one I think. Outer one is a bit weird. 
- Also, status variable may not be necessary as it is suggested by the customer in the [customer meeting 4](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-4).

**Comment by canberkboun9** [comment]
- Outer alternative is redundant because we should not assume that creating and object will be unsuccessful.  
- Status needs to be changed as we talked in Meeting 6.3 and [Customer Meeting 4](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-4).

**Comment by canberkboun9** [comment]
The changes were made.

**Comment by mehmetemreakbulut** [comment]
Everythink looks fine. I am closing the issue.
