### ISSUE TITLE
Final Milestone Deliverables

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#538]
***Description*:**

- The initial structure of the final milestone deliverables is structured.
- The final milestone folder and the deliverables inside can be found on [this link](https://github.com/bounswe/bounswe2022group5/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_3).
- Every member should complete the related parts for the individuals.
- As in the previous milestone, I will take care of the screenshots of the web application for the User Interface / User Experience part of the [Group Report](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/FM_Report_Group5.md).

***Reviewer*:** @mehmetemreakbulut @palahb            

***Task Deadline*:** 02.01.2023 12:00
***Review Deadline*:** 02.01.2023 17:00

**Comment by canberkboun9** [comment]
- Links are broken.

**Comment by mehmetemreakbulut** [comment]
LGTM! Closing issue!
