### ISSUE TITLE
Creating a Sequence Diagram for Proposing Article

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#54]
**Description:**
Creating a Sequence Diagram of a use case for proposing an article in the application. 

**Reviewer:** @Keremgunduz7 

**Task Deadline:** 10.04.2022 12.00
**Review Deadline:** 11.04.2022 15.00

**Comment by kardelendemiral** [comment]
I finished the diagram with the suggestions of other assignees. After all sequence diagrams are finished, I'll check it again to see if some things need to be changed to provide consistency. Other than that, a review might be beneficial.

**Comment by kardelendemiral** [comment]
We made some modifications according to customer meeting 3:
- Deleted UI since it is not an object.
- Colorized the diagram.

Needs review.

**Comment by Keremgunduz7** [comment]
First of all, I am sorry that the review has been late.
I think the design demonstrates lifespans and usage of the classes and functions well. It seems clear and understandable, needs not any more improvements at this stage.
Except, maybe we can add the types of the inputs with colons after the inputs, such as proposeArticle(title: string, body: string ...).
But again, I don't think this is a must, it can stay as it is.
All in all, great work done, thanks a lot to all contributors.

**Comment by mehmetemreakbulut** [comment]
We can consider @Keremgunduz7's suggestions together with the feedback we received from customer. It looks pretty good as it stands.

**Comment by kardelendemiral** [comment]
Thank you for the review. I added the types of parameters to the function calls as @Keremgunduz7 suggests. Seems like we finished the diagram and no more improvement is needed. I am closing the issue.
