### ISSUE TITLE
[Final Milestone] Status of the requirements

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#541]
***Description*:**

Explanation for status of the requirements will be added to our [final milestone report](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/FM_Report_Group5.md).

***Todo's*:**

- [x] Determining and adding the status of the requirements.

***Reviewer*:** @canberkboun9  

***Task Deadline*:** 01.01.2022 20:00
***Review Deadline*:** 02.01.2022 15:00

**Comment by enginoguzhansenol** [comment]
The [status of the requirements](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/FM_Report_Group5.md#status-of-the-requirements) are added to the Final Milestone report. There are some differences for each teams. These differences have been tried to be adequately stated. According to review some requirements or their status can be edited.

**Comment by canberkboun9** [comment]
#### Review
- I edited some typos.
- Added an explanation for the last requirement about search.
- Good job! Thank you Oğuzhan!
- Issue is open for now for caution, we can close it later.
