### ISSUE TITLE
Milestone 3 Customer Presentation Notes

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#542]
***Description*:**

- The [notes](https://github.com/bounswe/bounswe2022group5/wiki/Milestone-3-Presentation-Notes) taken during the presentation will be shared on the wiki page.

***Reviewer*:** @mehmetemreakbulut           

***Task Deadline*:** 02.01.2023 17:00
***Review Deadline*:** 02.01.2023 20:00

**Comment by mehmetemreakbulut** [comment]
LGTM!
