### ISSUE TITLE
[Final Milestone] Standards and Annotation Status

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#544]
***Description*:**
Adding Standard and Annotation Status to [Group Milestone Report](https://github.com/bounswe/bounswe2022group5/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_3#:~:text=.%E2%80%8A.-,FM_Report_Group5.md,-Update%20FM_Report_Group5.md)

***Reviewer*:** @canberkboun9 

***Task Deadline*:** 02.01.2022 20:00
***Review Deadline*:** 02.01.2022 21:00

**Comment by mehmetemreakbulut** [comment]
Standards and Annotation Status is added to [Final Milestone Deliverables](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/FM_Report_Group5.md)

**Comment by canberkboun9** [comment]
- Link is broken on this line: "In Milestone 2 and Customer Demo we have explained how we will implement Annotations with [the Annotation Mockup](https://github.com/bounswe/bounswe2022group5/wiki#:~:text=Annot-,Annotation%20Mockup,-%F0%9F%8F%A0)."
- I edited the titles here: [See](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/FM_Report_Group5.md#annotation-status)

**Comment by mehmetemreakbulut** [comment]
I fixed the link. You can close the issue.

**Comment by canberkboun9** [comment]
Thanks! Closing the issue.
