### ISSUE TITLE
[Final Milestone] API Section

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#545]
***Description*:**
Adding API Documentation Link and Collection to [Group Milestone Report](https://github.com/bounswe/bounswe2022group5/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_3#:~:text=.%E2%80%8A.-,FM_Report_Group5.md,-Update%20FM_Report_Group5.md)

***Reviewer*:** @canberkboun9 

***Task Deadline*:** 02.01.2022 20:00
***Review Deadline*:** 02.01.2022 21:00

**Comment by mehmetemreakbulut** [comment]
API Section added to [Group Milestone Report](https://github.com/bounswe/bounswe2022group5/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_3#:~:text=.%E2%80%8A.-,FM_Report_Group5.md,-Update%20FM_Report_Group5.md)

**Comment by canberkboun9** [comment]
Nice work, seems complete, thank you!
