### ISSUE TITLE
[Final Milestone] Executive Summary

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#546]
***Description*:**
Adding Executive Summary to [Group Milestone Report](https://github.com/bounswe/bounswe2022group5/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_3#:~:text=.%E2%80%8A.-,FM_Report_Group5.md,-Update%20FM_Report_Group5.md)

***Reviewer*:** @canberkboun9 

***Task Deadline*:** 02.01.2022 20:00
***Review Deadline*:** 02.01.2022 21:00

**Comment by mehmetemreakbulut** [comment]
Executive Summary added to [Group Milestone Report](https://github.com/bounswe/bounswe2022group5/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_3#:~:text=.%E2%80%8A.-,FM_Report_Group5.md,-Update%20FM_Report_Group5.md).

Need Review @canberkboun9

**Comment by canberkboun9** [comment]
- Well written, congratulations and thank you!
- I edited typos and errors.
- Status of Deliverables will be done, after that we can close the issue
