### ISSUE TITLE
[Final Milestone] FrontEnd System Manual 

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#548]
***Description*:**

**Part a.** in the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md) 

This issue is mainly about the System Manuel for FrontEnd Web Application.

***Todo's*:**

- [x] Writing the System Manual
- [x] Adding Instructions.

***Reviewer*:** @yavuuzsameet 

***Task Deadline*:** 02.12.2022 22:00
***Review Deadline*:** 02.12.2022 23:00

**Comment by Keremgunduz7** [comment]
System manual will be documented on the previously opened page [FrontEnd Manuals](https://github.com/bounswe/bounswe2022group5/wiki/FrontEnd-Manuals).

**Comment by Keremgunduz7** [comment]
Added Instructions and steps on to the page. You can reach it [here](https://github.com/bounswe/bounswe2022group5/wiki/FrontEnd-Manuals#system-manual).

Review Requested.

**Comment by yavuuzsameet** [comment]
Utterly great documentation. Grateful.
