### ISSUE TITLE
[Final Milestone] Other Project Artifacts: Part B, C, E, F

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#549]
***Description*:**

**Part b, c, e, f.** in the [Project Artifacts](https://github.com/bounswe/bounswe2022group5/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/Project%20Artifacts.md) 
Part a and d is nearly complete and they are documente with issues. This issue is for the other parts.

***Todo's*:**

- [x] Software Requirements Specification (SRS)
- [x] Software design documents (using UML)
- [x] Project plan
- [x] Unit tests

***Reviewer*:** @mehmetemreakbulut 

***Task Deadline*:** 02.12.2022 23:00
***Review Deadline*:** 02.12.2022 23:30

**Comment by canberkboun9** [comment]
Other parts are added.

**Comment by mehmetemreakbulut** [comment]
LGTM!
