### ISSUE TITLE
Creating a Sequence Diagram for Creating a Discussion Thread

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#55]
#### Description:
A sequence diagram for creating a discussion thread will be created and will be uploaded to the relevant page that will be later created.

Reviewer: @yavuuzsameet 
#### Review Deadline: 11.04.2022 - 23:59 GMT+3

**Comment by yavuuzsameet** [comment]
The methods in the diagram are consistent with the class diagram. All is good for now.

**Comment by yavuuzsameet** [comment]
The class names which represent objects can be moved to the same upper level on the diagram to be consistent with other group members' diagrams. Nothing to add apart from that. Nice work!

**Comment by palahb** [comment]
These are at that level since they are created afterwards, they are not present at the start of the diagram. I did them in that way since I have seen similar examples in repos from previous years.

**Comment by palahb** [comment]
Sequence diagrams are done. We can close the issue.
