### ISSUE TITLE
Creating a Sequence Diagram for Reporting a Comment

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#58]
#### Description: 
A sequence diagram for reporting a comment will be created and will be uploaded to the relevant page.

**Comment by oguzhandemirelx** [comment]
Deadlines are postponed due to the extension given by the instructor.

**Comment by oguzhandemirelx** [comment]
I finished the diagram with the help of other assignees. It needs some review for the improvement.

**Comment by Keremgunduz7** [comment]
It is compact and nice at this stage. I don't think that it needs some more details, explains the situation and the usage well.

**Comment by bbenginbestas** [comment]
I reviewed the diagram and I don't see anything missing. It looks correct and well-made.

**Comment by oguzhandemirelx** [comment]
Closing the issue for now, thanks for the reviews.
