### ISSUE TITLE
Creating a Sequence Diagram for Editing Post, Adding Location

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#59]
#### Description:
A sequence diagram for editing a post, for example, adding location to own post will be created and will be uploaded to the relevant page that will be later created, according to the action item 11 in [Meeting 5.3](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-5.3).

Reviewer: @burakmert236 
#### Review Deadline: 10.04.2022 - 15:00 GMT+3

**Comment by canberkboun9** [comment]
I almost finished this sequence diagram. Got some help from kardelen.
Also, helped others meanwhile. During this, deadline is changed, so we are relaxed and stopped working after some discussion about each other's work. I will continue working on this sequence diagram later.

**Comment by canberkboun9** [comment]
We made some editions to the ground work according to Customer Meeting 3 (to be uploaded). Then pretty much finished it, including colorization. It needs review.

**Comment by canberkboun9** [comment]
Added a message "s.searchDiscussionThread ByAuthor(author: Member)"

**Comment by canberkboun9** [comment]
changed "save" to "update" according to answers in Slack Channel mentioned in [Meeting 6.1 Notes](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-6.1).

**Comment by burakmert236** [comment]
I think fetching discussion threads must be held through database. SearchEngine should't do all fetching task by itself. Other than this, the diagram seems pretty nice.

**Comment by canberkboun9** [comment]
Will look into it.

**Comment by canberkboun9** [comment]
I made editions to achieve consistency in the diagram.
