### ISSUE TITLE
Modifying the README document of our repository

### ISSUE THREAD

**Issue by kardelendemiral** [bounswe/bounswe2022group5#6]
README file of our repository needs to be modified since it is empty.

**The README file will include:**

- Information about the group.
- Link to the home wiki page for more information.
- Links to personal wiki pages for each member.

**Comment by kardelendemiral** [comment]
- Added a description section for our group and a link to our home wiki page.
- Added the links to our members' personal wiki pages for those who have prepared their pages.

Other members can add their wiki page links when they prepare them.

**Comment by Keremgunduz7** [comment]
Suggestion:
Maybe we can take a picture of our group on our next meeting and include it to page.

**Comment by canberkboun9** [comment]
### Review:
- Looks great to me! We don't need an elaborate README document yet.

**Comment by enginoguzhansenol** [comment]
Added the link of my personal wiki page to the README document.

> * Added a description section for our group and a link to our home wiki page.
> * Added the links to our members' personal wiki pages for those who have prepared their pages.
> 
> Other members can add their wiki page links when they prepare them.

**Comment by kardelendemiral** [comment]
Every member finished adding their personal wiki pages. Closing the issue.
