### ISSUE TITLE
Use Case Diagram Design and Documentation

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#60]
#### Description:
For the assignment this week, Use Case Diagram is designed with teamwork effort. Its page will be opened, document will be uploaded properly.  

Reviewer: @yavuuzsameet 
#### Review Deadline: 14.04.2022 - 20:00 GMT+3

**Comment by yavuuzsameet** [comment]
I have spotted some spelling mistakes in the Use Case Diagram and corrected them before uploading it to GitHub.

**Comment by canberkboun9** [comment]
@enginoguzhansenol had uploaded the image but it's quality/resolution was low. Thus, I uploaded a new one.

**Comment by yavuuzsameet** [comment]
Fabulous!
