### ISSUE TITLE
Creating a Sequence Diagram for Modifying Personal Info

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#61]
Creating a Sequence Diagram for Modifying Personal Info as a use case. Registered Users shall be able to modify their personal information from their profile.

Reviewer: @oguzhandemirelx 

Task Deadline: ~~06.04.2022 12.00 GMT+3~~ 10.04.2022 22.00 GMT +3
Review Deadline: ~~06.04.2022 15.00 GMT+3~~ 11.04.2022 22.00 GMT +3

**Comment by yavuuzsameet** [comment]
Deadlines are postponed due to the extension given by the instructor.

**Comment by yavuuzsameet** [comment]
The first model of the diagram is available on lucidchart. I have contacted TA, and currently waiting to receive feedback. The diagram may be changed, or maybe left as it is.

**Comment by yavuuzsameet** [comment]
The diagram is now updated with a minor addition.

**Comment by yavuuzsameet** [comment]
After meeting with the customer during PS, the diagram has reached its final version. @oguzhandemirelx can review the diagram and close the issue afterwards.

**Comment by oguzhandemirelx** [comment]
Your diagram clearly explains everything about modifying personal info.  I can close the issue, excellent work!
