### ISSUE TITLE
Creating a Sequence Diagram for Rating a Comment

### ISSUE THREAD

**Issue by bbenginbestas** [bounswe/bounswe2022group5#63]
**Description:**

A sequence diagram for rating a comment will be created and will be uploaded to the relevant page.

**Reviewer: @enginoguzhansenol**

**Task Deadline: 10.04.2022 - 22:00 GMT+3**
**Review Deadline: 11.04.2022 - 22:00 GMT+3**

**Comment by bbenginbestas** [comment]
We finished the sequence diagram. We need review for the diagram we created.

**Comment by bbenginbestas** [comment]
Splitted the sequence diagram as 'Upvote' and 'Downvote'. Splitted each of them as 'successful' and 'failed'.

**Comment by bbenginbestas** [comment]
Filled the four parts mentioned in the previous comment. Finished the sequence diagram, it needs review.

**Comment by mehmetemreakbulut** [comment]
After our meeting I checked the diagram. Contributions are done. It clearly explains important points.

**Comment by enginoguzhansenol** [comment]
Lifelines and alternative scenarios look excellent. We can close the issue after our discussion in the next meeting. Great work!
