### ISSUE TITLE
Customer Meeting 3 Notes

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#64]
#### Description:
I took some notes in the [Customer Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-3). Created the page for it. It needs some edition and then to be uploaded into the related page.

Reviewer: @palahb

**Comment by canberkboun9** [comment]
I filled the page, it needs review.

**Comment by Keremgunduz7** [comment]
According to my notes that I have taken in the meeting, there is no more items to add to the feedbacks.
Thanks again for your effort in terms of collecting and documenting these items.

**Comment by palahb** [comment]
It seems pretty good. Thank you for all your efforts!

**Comment by canberkboun9** [comment]
Thank you, closing the issue.
