### ISSUE TITLE
Creating a Sequence Diagram for Chatbot Dialogue

### ISSUE THREAD

**Issue by busetolunay** [bounswe/bounswe2022group5#65]
Chatbot Dialogue Diagramas. Registered Users shall be able to receive suggestions from the Chatbot after a Q&A.  
Reviewer: @canberkboun9   
Task Deadline: 11.04.2022 12.00 GMT+3 12.04.2022 22.00 GMT +3

**Comment by canberkboun9** [comment]
We worked on the Chatbot Dialogue Sequence Diagram. It is finished.
