### ISSUE TITLE
Creating an Executive Summary for Milestone 1 Report

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#66]
**Description:**

An executive summary for our Milestone 1 Report will be created in the common Google Docs file that we created in [Meeting 6.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-6.2).

**Reviewer: @bbenginbestas**

**Task Deadline: 14.04.2022 - 14:00 GMT+3**
**Review Deadline: 14.04.2022 - 20:00 GMT+3**

**Comment by kardelendemiral** [comment]
I filled the Introduction and Description parts of the executive summary. A review might be good.

**Comment by bbenginbestas** [comment]
I reviewed the _Introduction_, _Description_, _Project Status_ and _Moving Forward_ parts of the _**Executive Summary**_. It looks great and I can't think of anything to add. Great documentation and explanations.

**Comment by palahb** [comment]
Thank you. I am closing the issue.
