### ISSUE TITLE
Creating Evaluation of the Status of Deliverables for Milestone 1 Report

### ISSUE THREAD

**Issue by mehmetemreakbulut** [bounswe/bounswe2022group5#67]
**Description:**

Evaluation of the Status of Deliverables for our Milestone 1 Report will be created.

**Reviewer: @kardelendemiral @palahb *

**Task Deadline: 14.04.2022 - 14:00 GMT+3**
**Review Deadline: 14.04.2022 - 20:00 GMT+3**

**Comment by mehmetemreakbulut** [comment]
These deliverables are evaluated. We will need review after final edits:
* Communication Plan
* Requirements
* Scenarios and Mockups
* Use Case Diagram
* Class Diagram
* Sequence Diagrams
* Project Plan & RAM

**Comment by makifyilmaz** [comment]
Added evaluations about Class Diagram, Sequence Diagram and Project Plan & RAM. The evaluation about Project Plan & RAM is uncomplete and will be finished after we finish preparing the Project Plan & RAM.

**Comment by mehmetemreakbulut** [comment]
Everything looks fine. I am closing the issue.
