### ISSUE TITLE
Creating a title page with the names of contributors to milestone 1.

### ISSUE THREAD

**Issue by Keremgunduz7** [bounswe/bounswe2022group5#68]
As stated in the description of Milestone 1 Deliverables. A title page should be created with course names, group number and contributors.

#### Review Deadline 14.04.2022 20:00

Reviewer: @busetolunay

**Comment by Keremgunduz7** [comment]
Together with @oguzhandemirelx we have designed and inserted the title page to our milestone report 1. Maybe @busetolunay  you can review it before we close the issue.

**Comment by busetolunay** [comment]
It seems fine, no need to make edits. We can close the issue.
