### ISSUE TITLE
Creating Evaluation of Tools and Processes for Milestone 1 Report

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#69]
Description:

Evaluation of Tools and Processes for our Milestone 1 Report will be documented and will be shared with group members.

Reviewer: @mehmetemreakbulut 

Task Deadline: 14.04.2022 - 14:00 GMT+3
Review Deadline: 14.04.2022 - 20:00 GMT+3

**Comment by yavuuzsameet** [comment]
The following will be evaluated:
- Slack
- Google Meets
- Discord
- Zoom
- Figma
- Lucidchart
- ProjectLibre
- Google Sheets
- Google Docs

**Comment by yavuuzsameet** [comment]
I have evaluated the elements above and documented them on the file. @mehmetemreakbulut can review and close the issue.

**Comment by mehmetemreakbulut** [comment]
I have reviewed the evaluation of tools and processes for Milestone 1 Report. Everything seems fine. We can close the issue.

**Comment by yavuuzsameet** [comment]
Okay, closing the issue.

**Comment by yavuuzsameet** [comment]
Added GitHub to the evaluation list, and evaluated right after.
