### ISSUE TITLE
Creating wiki page for the research about favourite repos

### ISSUE THREAD

**Issue by makifyilmaz** [bounswe/bounswe2022group5#7]
#### Description:
A wiki page for displaying the collective result of our research about favourite github repositories mentioned in Assignment1 needs to be created. The research results should include name of the repo, link to the repo and a description.

#### To Do:
* Create a wiki page for research results
* Add a research result template as example

**Comment by makifyilmaz** [comment]
Added a wiki page for the research results with a sample template. Members can add their research results to [this page](https://github.com/bounswe/bounswe2022group5/wiki/Repositories-We-Like) .

**Comment by Keremgunduz7** [comment]
Created a template section to follow while adding research results.
