### ISSUE TITLE
Documenting Customer Meeting 4 Notes

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#70]
**Description:**

A page for [customer meeting 4](https://github.com/bounswe/bounswe2022group5/wiki/Customer-Meeting-4) will be created and the notes taken during the PS (13.04.2022) will be documented.

Reviewer: @Keremgunduz7 

**Task Deadline: 14.04.2022 - 14:00 GMT+3**
**Review Deadline: 14.04.2022 - 20:00 GMT+3**

**Comment by yavuuzsameet** [comment]
I created the page and uploaded the meeting notes, now it can be reviewed or can be edited with additional notes taken by group members during the meeting.

**Comment by canberkboun9** [comment]
Maybe we could add the link to the page here

**Comment by yavuuzsameet** [comment]
> Maybe we could add the link to the page here

Done.

**Comment by Keremgunduz7** [comment]
Seems nothing missing. Feedbacks are written clear and understandable, thanks for the effort.

**Comment by yavuuzsameet** [comment]
Closing the issue then.
