### ISSUE TITLE
Gathering Deliverables for Milestone 1 Report

### ISSUE THREAD

**Issue by enginoguzhansenol** [bounswe/bounswe2022group5#71]
Deliverables will be added to the Milestone 1 Report.

**Reviewers:** @oguzhandemirelx, @makifyilmaz 

**Task Deadline:** 14.04.2022 - 14:00 GMT+3
**Review Deadline:** 14.04.2022 - 20:00 GMT+3

**Comment by canberkboun9** [comment]
We gathered the deliverables and edited typos, made adjustments for consistency in Diagrams, Scenarios&Mockups, and Requirements
