### ISSUE TITLE
Class Diagram design and documentation

### ISSUE THREAD

**Issue by canberkboun9** [bounswe/bounswe2022group5#74]
#### Description:
For the assignment this week, Class Diagram is designed with teamwork effort. Its page will be opened, document will be uploaded properly.  

Reviewer: @palahb, @Keremgunduz7 
#### Review Deadline: 14.04.2022 - 20:00 GMT+3

**Comment by canberkboun9** [comment]
@enginoguzhansenol uploaded the [Class Diagram](https://github.com/bounswe/bounswe2022group5/wiki/Class-Diagram) to the Wiki, but, image but it's quality/resolution was low. Thus, I uploaded a new one.

**Comment by palahb** [comment]
Seems quite good. Thank you!
