### ISSUE TITLE
Creating Deliverables Wiki Page

### ISSUE THREAD

**Issue by yavuuzsameet** [bounswe/bounswe2022group5#75]
**Description:**

A wiki page to store the M1-Group-5-Deliverables.pdf on the GitHub. The pdf will be added to the page after all deliverables are gathered by @enginoguzhansenol.

**Reviewer:** @canberkboun9 

**Task Deadline: 15.04.2022 - 19:00 GMT+3**
**Review Deadline: 15.04.2022 - 22:00 GMT+3**

**Comment by yavuuzsameet** [comment]
The page is created, @enginoguzhansenol will add the pdf to the page.

**Comment by canberkboun9** [comment]
I changed the page into Project Plan page by misunderstanding. I will create a new one and add it to the Sidebar.

**Comment by canberkboun9** [comment]
I created a new page. @enginoguzhansenol will upload the deliverables into it.

**Comment by yavuuzsameet** [comment]
Page created, file uploaded.
