### ISSUE TITLE
Practice App: Uploading The Initial Structure

### ISSUE THREAD

**Issue by palahb** [bounswe/bounswe2022group5#79]
#### Description:
The initial implementation of our practice app that we created during our [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2) will be uploaded. It includes the initial structure of our project, apps, and models. Everyone can start working on their endpoint.

Reviewer: @yavuuzsameet @mehmetemreakbulut 
#### Review Deadline: 08.05.2022 - 20:00 GMT+3

**Comment by palahb** [comment]
I uploaded the initial structure. This issue is linked to the pull request [#80](https://github.com/bounswe/bounswe2022group5/pull/80) and will be closed when the pull request is merged.

**Comment by canberkboun9** [comment]
I added windows commands to the README file. Can you review it @palahb, please

**Comment by palahb** [comment]
I checked it and added necessary Linux/macOS commands. Thanks.
