### ISSUE TITLE
Creating a Discord Channel for weekly group meetings

### ISSUE THREAD

**Issue by burakmert236** [bounswe/bounswe2022group5#9]
## Communication Platform: Discord

To have better communication during our weekly meetings, we will use a Discord channel. Discord will be useful in the context of in-meeting documentation especially. Some benefits of using Discord:
 - We will be able to access chat for previous meetings. 
 - We might develop different Discord bots when an according need arises.

**Comment by bbenginbestas** [comment]
We created the discord channel. We will improve it with different features over time.
