### ISSUE TITLE
Practice App: Implementing the API for Rate Post

### ISSUE THREAD

**Issue by oguzhandemirelx** [bounswe/bounswe2022group5#96]
### Description
According to the endpoints that determined by the group in the [Meeting 10.2](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-10.2), rate-post functionalities should be implemented.

We have distributed the tasks among 12 group mates and my main responsibility is to implement rate-post endpoint and API.

Together in the Meeting 10.2, as stated in issues [#78](https://github.com/bounswe/bounswe2022group5/issues/78) and [#79](https://github.com/bounswe/bounswe2022group5/issues/79), we have decided on the models and pushed them to our GitHub.

Main functionality of the rate-post part of the project is that,
- Getting number of upvotes and downvotes of a post with a specific ID as the GET part of API
- Upvoting or downvoting a post with a specific id as the POST part of API

### Details of the rate-post API:
- [x] Check whether the given data is valid or not. 
- [x] Check whether the post with the given post-id exists.
- [x] Updating and saving posts, or getting posts.
- [x] Success or Error Response.
- [x] Documentation.
- [x] Postman Test.
- [x] Saving to Postman.
- [x] Unit tests.

Requests and responses will be documented by using Postman.

Documentation: [Postman](https://documenter.getpostman.com/view/21009453/Uyxkik1p)

#### Review Deadline: ~14.05.2022~ 17.05.2022 20:00  

Reviewers: @mehmetemreakbulut @enginoguzhansenol

**Comment by oguzhandemirelx** [comment]
Get and Post endpoints, unit tests are done. Documentation prepared. I added documentation link to the issue.

**Comment by mehmetemreakbulut** [comment]
Everything looks fine. We can close the issue.
